### ISSUE TITLE
Embedded dashboard: "maximize" button not working

### ISSUE THREAD

**Issue by lgdocomo** [awslabs/amazon-quicksight-embedding-sdk#10]
It could be a mistake on our part, but it looks like that when we **embed QuickSight dashboard** in our page and click on **"maximize" button**, in any chart, **seems not working**.
If we do the same test directly on quicksight dashboard (**not embedding**) **it works correctly**.

Is it a bug? or maybe something I'm doing wrong?

**Comment by mark-hayward** [comment]
When I press it, using Chrome, the chart's legend appears and disappears.

**Comment by lgdocomo** [comment]
> When I press it, using Chrome, the chart's legend appears and disappears.

Yes, the chart's legend appears, but I was thinking that maximize button should have shown me the expanded chart like in quicksight dashboard (not embedded).

Maybe is there another method to do this?

Here the current situation:
- on embedded dashboard when click on maximize button I see the normal chart
![chart_expanded_embedded](https://user-images.githubusercontent.com/51404761/59020653-b957b080-884a-11e9-97ee-dee80c931a73.png)

- on **not** embedded dashboard when click on maximize button I see the **Expanded** Dashboard
![chart_expanded](https://user-images.githubusercontent.com/51404761/59020652-b8bf1a00-884a-11e9-99da-2f3b35560a8a.png)

**Comment by giano** [comment]
Same here

**Comment by cxiangna** [comment]
Thank you guys for letting us know. After discussing with our product managers, we are going to hide the maximize button in next QuickSight release as they think "maximize" doesn't really fit embedded view use case. I will keep you guys updated.

**Comment by DDdanielagualtieri** [comment]
Hi Cxiangna, I don't think the button should disappear, also because with this the customers will have even less chance to make analysis in mobility as the screen is very small and they cannot enlarge the chart. Moreover your competitors (like PowerBI and Qlik Sense) have this embedded functionality so it would be very apprecciated if you can spend sometime to fix it instead of removing (that said from a product manager ;)). BR Daniela

**Comment by jcardus** [comment]
Maximize is a very important feature. When will it be fixed? I'm also waiting on this.

**Comment by jcardus** [comment]
Any news on this?

**Comment by cxiangna** [comment]
This issue is fixed.

**Comment by swathipothula20** [comment]
Still we see this issue with latest version RubyGem-aws-sdk-quicksight - 1.6.x .

**Comment by ShahinFelkees** [comment]
Hi,Please tell how to increase size of the dashboard in quicksight
