### ISSUE TITLE
Embedding gives error in Safari iOS

### ISSUE THREAD

**Issue by hardikdgsa** [awslabs/amazon-quicksight-embedding-sdk#102]
I integrated Quicksight into the Angular web app. 
It works well with the Desktop Safari, Chrome browsers, Android browsers. 
It even works in incognito. of the same. 

However, when I try to open the website in the iOS Safari browser(iOS Version 13.5- iOS 15.2), it shows errors, and the data is not loaded. 

[Error] Blocked a frame with origin "https://us-east-1.quicksight.aws.amazon.com" from accessing a frame with origin "https://current-domain". Protocols, domains, and ports must match.
[Error] Failed to load resource: A server with the specified hostname could not be found. (embedding.a85b2c753bb5d7d889af.36.js.map, line 0)

Anyone has implemented a solution specific for iOS safari browsers. 
I have found some answers to using Nginx reverse proxy kind of implementation, though it required a good amount of configuration

**Comment by zzhengyi-amazon** [comment]
Hello,

Did you follow https://docs.aws.amazon.com/quicksight/latest/user/approve-domain-for-dashboard-embedding.html to add domain allow list? If yes, and still face the issue, could you contact AWS Support and cut a ticket to QuickSight Embedding team? Thanks.
