### ISSUE TITLE
Localization not being handled correctly in embedded dashboard markup

### ISSUE THREAD

**Issue by nbaltatzis** [awslabs/amazon-quicksight-embedding-sdk#103]
There are a couple localization issues:

1) The html element needs to have the `lang` attribute set correctly. Right now it is always to set to `en`, regardless of what locale is passed in to the embedding options.

2) The <title> tag value set in the html <head> section is not localized. It always says "Dashboard" in English, when it really should be localized to be in the language set in the locale. 

That title will also need to be set correctly on the iframe for AX compliance, but I am filing a separate issue for that.

Example of current markup when I set the locale to `es_ES`:

```
<html lang="en"><head>
    <meta charset="utf-8">
    ...
    <title>Dashboard</title>
    ...
</html>
```

**Comment by nbaltatzis** [comment]
Another potential thing to think about is just exposing an option to consumers that allows them to override the title with whatever they want. This would at least provide the opportunity for consumers to do the localization on their end and just pass in the value they want to use. Just make sure to use it for both the iframe title attribute and the <title> element in the html <head>. See: https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/104

**Comment by bwelkin** [comment]
`contentOptions.onMessage` in the v2 provide a reference to the iframe in its second argument. Developers can easly set a custom title for the iframe.


```
{
    ...
    onMessage: (messageEvent, metadata) => {
        const {eventName} = messageEvent; 
        const {frame} = metadata; 
        switch (eventName) {
            ...
            case 'CONTENT_LOADED': {
                frame.title = '<YOUR_CUSTOM_IFRAME_TITLE_HERE>';
                break;
            }
            ...
        }
    },
    ...
}
```

**Comment by mvazan** [comment]
> `contentOptions.onMessage` in the v2 provide a reference to the iframe in its second argument. Developers can easly set a custom title for the iframe.
> 
> ```
> {
>     ...
>     onMessage: (messageEvent, metadata) => {
>         const {eventName} = messageEvent; 
>         const {frame} = metadata; 
>         switch (eventName) {
>             ...
>             case 'CONTENT_LOADED': {
>                 frame.title = '<YOUR_CUSTOM_IFRAME_TITLE_HERE>';
>                 break;
>             }
>             ...
>         }
>     },
>     ...
> }
> ```

This is not a valid answer because it refers to the frame's title attribute, but the request was about the title inside the HTML document in the iframe. Its value is still set to `Dashboard` and not localized.

**Comment by mvazan** [comment]
@bwelkin, can you please validate my last comment?
