### ISSUE TITLE
CRSF error .

### ISSUE THREAD

**Issue by erkanisuf** [awslabs/amazon-quicksight-embedding-sdk#107]
I am in need of help , since cant figure out this.
I am genereting the url via nodejS:

>         
           const experienceConfiguration = {
		"Dashboard": {
			"InitialDashboardId": "mydashid"
		}
	};
	quicksight.generateEmbedUrlForAnonymousUser({
		'AwsAccountId': 'myid',
		'Namespace': 'default',
		'AuthorizedResourceArns': ["arn:aws:quicksight:eu-west-1:myid:dashboard/mydashId"],
		'ExperienceConfiguration': experienceConfiguration,
		'SessionLifetimeInMinutes': 600
	}, function (err, data) {
		console.log('Errors: ');
		console.log(err);
		console.log('Response: ');
		console.log(data);
	})
})

This seems to work fine, and it returns me status code 200 and EmbedUrl. When i copy paste this url and put it in the browser it opens the dashboard view to me. But when i put the embedUrl to react this way:

> 
                 useEffect(() => {
			let dashboard

			function onDashboardLoad(payload) {
				console.log("Do something when the dashboard is fully loaded.", payload);
			}

			function onError(payload) {
				console.log("Do something when the dashboard fails loading", payload);
			}

			function embedDashboard() {
				let containerDiv = document.getElementById("embeddingContainer");
				let options = {
					url: THE_LONG_EMBED_URL_HERE,
					container: containerDiv,
					height: "700px",
					width: "1000px",
				};
				dashboard = QuickSightEmbedding.embedDashboard(options);
				dashboard.on("error", onError);
				dashboard.on("load", onDashboardLoad);
			}

			function onCountryChange(obj) {
				dashboard.setParameters({country: obj.value});
			}

			embedDashboard()
		}, [])

When i look at the network tab in the browser and check the response i get status code: 401 with message:
`Message: "csrf token missing or not match."`. And the console.log from error call back says: `{errorCode: 'Unauthorized'}`
The rendered view also displays AWS logo with message:
`Embedding failed because of invalid URL or authorization code. Both of these must be valid and the authorization code must not be expired for embedding to work.`
I am testing it in localhost, and via https in heroku too .

**Comment by oorellana95** [comment]
HI! We have a similar issue. It seems that in our case half of the times it is working and the other half it is not working. If someone know how to solve it, I'd be really thankful.

We just get the embedUrl from the backend and we use:

`      embedDashboard({
        url,
        container: div,
        parameters,
        scrolling: 'no',
        locale: 'en-US',
        footerPaddingEnabled: true
      });
`

**Broken**
- Response: {"Message":"csrf token missing or not match."}

- Network tab:
![image](https://user-images.githubusercontent.com/67627437/152393683-975c89aa-495a-4f46-8bec-d9a23046b352.png)

- Header (Note: **Authorization** is missing)
![image](https://user-images.githubusercontent.com/67627437/152396214-3d76604f-48c0-4eab-b8d1-2e6512ba5aab.png)

**Working**
- ✅
![image](https://user-images.githubusercontent.com/67627437/152395201-9bf20049-3d18-4964-92dd-81566b1fb67b.png)
- Header (The request has Authorization*)
![image](https://user-images.githubusercontent.com/67627437/152396394-0f55256a-b431-4ae5-bbba-2f756f6d571c.png)

**Comment by erkanisuf** [comment]
Hello again.
Seems  like that my issue was because of permission in the AWS control panel of quicksight. The main administrator just had to add the url of the application (https) and it worked. So in local will not be available the view ,unless some "hacky" way to turn localhost to https. Also the url must be regenerated for every refresh , login , user etc.

**Comment by zzhengyi-amazon** [comment]
Hi, looks like issue resolved for erkanisuf. Resolve this issue.
