### ISSUE TITLE
Sizzle attribute constantly being added/removed

### ISSUE THREAD

**Issue by jpamador** [awslabs/amazon-quicksight-embedding-sdk#108]
I'm using the embedDashboard to embed a Quicksight Dashboard. It works fine and I don't see any errors, but if I inspect the iframe I see that there is an attribute being constantly added/removed to one of the divs:
![image](https://user-images.githubusercontent.com/4072509/151467089-b6072ec8-8c24-41db-bcb7-014f98e6d8c2.png)
![image](https://user-images.githubusercontent.com/4072509/151467121-a8bd4e35-fb9e-4efd-a37a-c4567ed81e14.png)
![image](https://user-images.githubusercontent.com/4072509/151467135-734641bb-5f3d-4de9-8d2f-2b6ced19814d.png)

Why is that happening? Is this expected?

**Comment by Dhairyasarous** [comment]
Hey is this still an issue? I could not repro this.
