### ISSUE TITLE
Error callback is not called

### ISSUE THREAD

**Issue by mark-hayward** [awslabs/amazon-quicksight-embedding-sdk#11]
Hello,
When I set up an error callback using this :

```
        var options = {
            url: dashboard.embedUrl,
            container: document.getElementById(dashboard.id),
            scrolling: "no",
            height: "AutoFit",
            loadingHeight: "300px",
            width: "100%"
        };

        let db = QuickSightEmbedding.embedDashboard(options);
        db.on("error", this.onDashboardError);
        db.on("load", this.onDashboardLoad);

```

When a valid page loads I successfully get a callback to onDashboardLoad but whenever a page fails due to an unauthorised error I do not get an error callback.

Any idea?

**Comment by apatlori** [comment]
We do send error callbacks for 401 and 403 errors. If you send us a screenshot of the error from the network tab, we can investigate the issue

**Comment by cmckni3** [comment]
is there a way to catch a 429 error?

**Comment by jimlitton** [comment]
Good day, can you please send back errors? Including HTTP errors?  Is there some other way to handle 401, 403, 404 errors in the embedded dashboard request?  Thanks,

**Comment by yang-f** [comment]
Ran into the same problem.

**Comment by Grace-Dmello** [comment]
Ran into the same issue. I am using an old embedded URL. So, as expected an error screen is displayed. However, error callback is not called. Tried with both ways below

```
const dashboard = QuickSightEmbedding.embedDashboard({
    url: '',
    errorCallback: (err) => console.log(' error', err);,
    container,
  });

// AND

dashboard.on("error", (err) => {
    console.log(' error', err);
  });
```

**Comment by subeshb1** [comment]
Ran into the same problem as well. When the URL is not valid we can't handle the error

**Comment by joyarunraj** [comment]
With latest JS SDK release, it should be possible to get error callbacks for expired embedding urls, invalid dashboard, access restricted dashboard. Please let us know if this is not the case, and you are still facing issues. We are working on adding callbacks for other error scenarios like embedding session expiry, which is different from url expiry.

**Comment by Grace-Dmello** [comment]
After upgrading the version `1.0.15`, the error callback worked for the invalid embedded URL scenario.

**Comment by hanstf** [comment]
Hi @joyarunraj, we are using version `1.0.17` and also facing the same issue where the error callback is not called when domain whitelisting is removed and when I put an invalid URL.

**Comment by thais-molica** [comment]
Any update in this? I'm facing the same issue, using version `1.18.0`

**Comment by naokomada** [comment]
I'm facing the same problem. (with version `1.18.0` )
I want to detect that a 429 error has occurred in the dashboard. But as of now, that is not possible.

**Comment by mzack5020** [comment]
+1 Same error here. Trying to detect error "Refused to frame '<URL>' because an ancestor violates the following Content Security Policy directive: "frame-ancestors ...". Can't get any of the callbacks to work. This is the current code: 
```
const dashboard = QuickSightEmbedding.embedDashboard(params);
dashboard.on('error', this.onError);
dashboard.on('load', this.onVisualLoaded);
```

**Comment by Dhairyasarous** [comment]
Hey,

We have verified that: 
1. Error callback is called correctly for 400, 401, 403, 404, and 500 error pages.
2. Confirmed that expired AuthCode triggers the 403 callback.
3. We are internally tracking a feature request for handling 429.

**Comment by thais-molica** [comment]
I've updated my package to version `1.19.0` and waited until my dashboard url expired. I got and 401 (Unauthorized) error, but it didn't triger the `errorCallback` yet.
