### ISSUE TITLE
Topics Not Appearing in Embedded Console

### ISSUE THREAD

**Issue by DivonC** [awslabs/amazon-quicksight-embedding-sdk#110]
I cannot seem to create topics or share topics with users in namespaces. The "Topics" icon does not appear in the embedded console. In addition, for namespace users, when I try embedding a q bar, the q bar embed url results in a blank iFrame. How can we go about providing access to the Q Bar / topics to users in namespaces with the API?

**Comment by deepaksmurthy** [comment]
QuickSight Q Authoring is not yet supported in the embedding SDK so you will not be able to create topics in an embedded QuickSight application, you can embed the Q bar in your application and use QuickSight for authoring topics. Once you have created topics in QuickSight they can be shared with other users within the same namespace. 

You can learn more about 
1. Embedding the Q bar - [here](https://docs.aws.amazon.com/quicksight/latest/user/embedded-analytics-q-search-bar-for-authenticated-users.html)
2. Sharing Q topics - [here](https://docs.aws.amazon.com/quicksight/latest/user/quicksight-q-topics-sharing.html)

**Comment by webauthor** [comment]
Is there an ETA on when this feature might be available?  Or at least the ability to create topics via the CLI tool?
