### ISSUE TITLE
setParameters cannot clear selection

### ISSUE THREAD

**Issue by BernabeFelixUb** [awslabs/amazon-quicksight-embedding-sdk#111]
I have an external control, for UI reasons, that calls `setParameters` to update a multi-value property. I would like to unselect all values in this property but if I use `setParameters( { [property]: [] } )`, nothing happens. I've tried using `''`, `undefined`, `null`, etc but nothing works, these values are considered a new option in the list.

Is this a bug or is intended behavior? if that's the case why?

**Comment by bwelkin** [comment]
Version 2.0 resolves this issue. Please try
```
const embeddingContext = await createEmbeddingContext();
...
const embeddedDashboard = await embeddingContext.embeddedDashboard(...);
...
embeddedDashboard.setParameters([
    {
        Name: '<YOUR_PARAMETER_NAME>',
        Values: []
    }
])
```

**Comment by mariadelacamara** [comment]
@bwelkin Hi! this did not fix the problem. We sent empty array but the old value remains there. The only way we can change the value is to select a different(s) one(s). So Idk why this support empty array when you first navigate to the dashboard,  but not after. Is there any solution for this?

PS:
onMessage: async (messageEvent) => {
                switch (messageEvent.eventName) {
                    case 'PARAMETERS_CHANGED': {
                        // messageEvent.message contains all parameters with active values
                        console.log(JSON.stringify(messageEvent.message));
                        break;
                    }
                }
            },
            
            When we clear the parameters and the param objet is 
            {
        Name: '<YOUR_PARAMETER_NAME>',
        Values: []
    }
    
    this message is still reflecting the old value. Not []
