### ISSUE TITLE
AutoFit height option causes huge quicksight content gaps when zooming in/out

### ISSUE THREAD

**Issue by CoryBond** [awslabs/amazon-quicksight-embedding-sdk#112]
Hey Team,

Right now a lot of the dashboards we embed use the AutoFit option for height simply so that we can make adjustments to our dashboards without worrying about adjusting the heights across our whole UI. However there is some weird behavior if the iframe has to resize between heights... basically the quicksight dashboard create this huge gap from the actual content to anything outside quicksight. This can easily be replicated if you zoom in/out of your browser.

![BehaviorWithAutoFit](https://user-images.githubusercontent.com/12073642/155761242-9cbf564e-510f-4c2f-9f32-9258829396ec.gif)

An alternative to doing this is to use "100%" height option but then if we don't specificy the exact wrapper div height there are alignment issues with the iframe:
![BehaviorWith100%Height](https://user-images.githubusercontent.com/12073642/155761136-fee414d5-f56a-4f63-a5ce-152d2aa65485.gif)

Is there a way to fix the "gap creation" issue when using "AutoFit" as our height? Like can we hook into a even of some type or call the dashboard API to do something to fix this? Any help would be appreciated!

**Comment by CoryBond** [comment]
Just a quick update, this behavior only happens in Firefox. If I test the same thing in Chrome there are no weird gap growths when repositioning/zooming iframe.

**Comment by jakemager** [comment]
I am also having this issue... In all browsers. However, I fixed it by putting an observer on the embedding container `#embeddingContainer` and when a child is present in the container it then sets the height to an arbitrary high number. This then triggers the quicksight iframe to resize to my `#embeddingContainer` height

```
const embeddingContainer = document.getElementById("embeddingContainer");
    if (embeddingContainer) {
      const observer = new MutationObserver(() => {
        embeddingContainer.children[0].height = 15000;
      });
      observer.observe(embeddingContainer, { childList: true, subtree: true });
    }
```

and my options for the embedDashboard
```
options = {
      url: dashboardUrl,
      container: "#embeddingContainer",
      scrolling: "no",
      height: "AutoFit",
      iframeResizeOnSheetChange: true,
      width: "100%",
      locale: "en-US",
      footerPaddingEnabled: true,
      sheetTabsDisabled: true,
      printEnabled: true,
      undoRedoDisabled: false,
      resetDisabled: false,
    }
``` 

I have a min height of `100vh` on the wrapper around `#embeddingContainer`

**Comment by bwelkin** [comment]
These seems to be related to width and height styling settings of the wrapping containers. In the Version 2, you can tap into the `SIZE_CHANGED` message events

```
const contentOptions = {
    // ...
    onMessage: (messageEvent, metadata) => {
        const {eventName, message} = messageEvent;
        const {frame} = metadata;
        switch (eventName) {
            // ...
            case 'SIZE_CHANGED': {
                const {width, height} = message;
                console.log('QuickSight content reported a size change', width, height);
                break;
            }
            // ...
        }
    },
    // ...
};
```
(`frame` in the above example is a reference to the iframe element created for the embedded experience)

Resolving the issue. Please feel free to submit a new issue if you observe the issue in the v2.
