### ISSUE TITLE
Dashboard on load event does not work in safari and firefox navigators.

### ISSUE THREAD

**Issue by alberto-perdiguero** [awslabs/amazon-quicksight-embedding-sdk#114]
This sentence does not work in safari and firefox navigator:

dashboard.on("load", vmDashboard_bi.dashboardLoadHandler);

Either does not work in the loadCallback parameter.

In this version:
amazon-quicksight-embedding-sdk@1.18.1

Navigators:

- Safari Version 14.0.1 (16610.2.11.51.8).
- FireFox (Last version).

I have to make a correction. The callback is executed, as long as the div containing the dashboard is visible. If you have the display:none style the callback function does not run.

**Comment by sonals-amazon** [comment]
Hello,

Is this still an issue? Were you able to resolve this?

**Comment by ben-gryps** [comment]
I am unable to get my callbacks to run when provided in the embedOptions of embedSession. I have provided an errorCallback and a loadCallback. Both simple run a console.log, but I see no console output.

**Comment by manueltarouca** [comment]
I'm having the same issue on Chrome. Both on **load** and on **error**.

**Comment by nabilarbouz** [comment]
I am still experiencing this issue as well.

**Comment by nabilarbouz** [comment]
@sonals-amazon any updates on this issue by any chance?

**Comment by bwelkin** [comment]
console embedding issue is tracked in https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/134
