### ISSUE TITLE
There is no way of getting what Controls each Sheet is using

### ISSUE THREAD

**Issue by arturopie** [awslabs/amazon-quicksight-embedding-sdk#115]
We want to allow our users to save the Control values they are using on each sheet. Each sheet in the same dashboard would have a different sets of Controls. From what I see in the docs, there doesn't seem to be a way of getting the controls the current sheet is using. 

I think this is something that could be passed to the `dashboard.on("selectedSheetChange", cb)` callback and/or `dashboard.getSheets(cb)` callback.

Thanks,

Arturo

**Comment by Dhairyasarous** [comment]
This is currently not supported via the QuickSight Embedding SDK. I am marking this as a feature request.

**Comment by jiajing28** [comment]
Persisting control values for registered users is now supported out-of-the with State Persistence and Bookmarks. Please see [reference](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-quicksight-state-persistence-bookmarks-embedded-dashboards/) for getting started.
