### ISSUE TITLE
setParameters ignores new values after QuickSight dashboard reset

### ISSUE THREAD

**Issue by hellhound1988** [awslabs/amazon-quicksight-embedding-sdk#116]
Hello,

we are noticing some incorrect behavior of `setParameters` method after doing reset in QuickSight dashboard. Here is the scenario:
1. have a multi-value input parameter for our dashboard, let's call it `ids`
2. call `embedDashboard` method with the initial value:
```
embedDashboard({
...
parameters: {
  ids: ['1']
},
...
});
```
3. call `setParameters` with a new value:
```
setParameters({
  ids: ['1', '2']
})
```
4. click "Reset" button in the embedded dashboard - this would reset the input parameter to the value that was provided at  `embedDashboard` call time (ids: ['1'])
5. call `setParameters` with a new value again:
```
setParameters({
  ids: ['1', '2']
})
```

Now, step 5 would do nothing, as if the embedding SDK had some sort of cache of the last set value. 
Setting it to any other new value (i.e. not ['1', '2']) would work correctly.

**Comment by Dhairyasarous** [comment]
We tried reproducing internally but could not. Can you open a support ticket with the QuickSight embedding team?

**Comment by sonals-amazon** [comment]
Closing since there has been no update on the issue.
