### ISSUE TITLE
DatePicker component won't hide itself

### ISSUE THREAD

**Issue by pt-kojoa** [awslabs/amazon-quicksight-embedding-sdk#117]
using this version to embed dashboard on webpage: `https://unpkg.com/amazon-quicksight-embedding-sdk@1.19.0/dist/quicksight-embedding-js-sdk.min.js`

Other UI components, like checkbox list, etc. hides itself when, for example, clicking dashboard background.

But Date picker pops back up and won't stay hidden when dashboard background is clicked.

**Comment by Dhairyasarous** [comment]
Hey is this specific to embedding SDK? Or does this also occur when accessing the console directly?

**Comment by pt-kojoa** [comment]
Happened only with embedding SDK, not with console. However, this no longer happens at all. Not sure if it was related to Firefox update.
