### ISSUE TITLE
Switching from one dashboard to another doesn't work

### ISSUE THREAD

**Issue by skined90** [awslabs/amazon-quicksight-embedding-sdk#118]
We faced strange issue with embedded dashboards.

We have next scenario:

There are 3 dashboards, dashboard1, dashboard2, and dashboard3. All of them are shared with the user.

When we generate the url for the dashboard1 and open it using this SDK, everything works correctly.
From the dashboard1, user is able to go to the next dashboard (in this case dashboard2) by clicking on some of the records and dashboard2 opens correctly. After that, user is able to go to the dashboard3 by clicking on some of the records in dashboard2 but it doesn't work as expected. It returns error that page can not be opened. 

We also tried to open it directly from the browser without using iframe. Behavior is quite same. The only difference is that instead of error, we get redirected to the login page of the quicksight.

We also tried to open firstly dashboard2 and then go to the dashboard3 and it works as expected.

Therefore, it seems that going further more than once doesn't work.

Is there any way to overcome this issue?

**Comment by Dhairyasarous** [comment]
Can you verify if you are using URL actions and not the navigate functionality from the embedding SDK.

If you are using URL actions here's some guidance on how to set that up. This is for navigating from dashboard1 -> dashboard2. You'll have to set up something similar for dashboard2 -> dashboard3 navigation. 

```
1. Create an analysis.

2. Create a URL Action to jump from current dashboard to 12345678-7476-4cc7-9c57-766b6bb5f123.
Activation: Menu Option
Action type: URL action
URL: <<$EmbedUrlRootPath>>/12345678-7476-4cc7-9c57-766b6bb5f123#p.EmbedUrlRootPath=<<$EmbedUrlRootPath>>

3. Create the following parameters
Name: EmbedUrlRootPath
DataType: String
Values: Single value
Open In: Same browser tab
Static default value: https://us-east-1.quicksight.aws.amazon.com/sn/dashboards/12345678-7476-4cc7-9c57-766b6bb5f123

4. Publish it as a dashboard. Test it within QS Website itself, it should work.

5. From embedding JS SDK, when setting up the dashboard parameters using the SDK, make sure to set the EmbedUrlRootPath parameter, like so:

var rootEmbedUrlPath = /^(https:\/\/[^/]+\/embed\/[^/]+\/dashboards)([^?]+)/gi.exec(embedUrl)[1]; // should give us something like: https://us-east-1.quicksight.aws.amazon.com/sn/dashboards
var params = {
    url: embedUrl,
    container: containerDiv, // other parameter values, will be different for your use case
    width: "1000px", // other parameter values, will be different for your use case 
    height: "AutoFit", // other parameter values, will be different for your use case
    parameters: {
        EmbedUrlRootPath: rootEmbedUrlPath // this is the parameter value you need to pass
    }
};
var dashboard = QuickSightEmbedding.embedDashboard(params);
```

**Comment by vishnubc** [comment]
Many thanks for the reference, @skined90.  Will explore the suggestion extended by @Dhairyasarous.  Were you able to resolve the issue or is this a limitation?

**Comment by sonals-amazon** [comment]
Is this still an issue?

**Comment by vishnubc** [comment]
Yes, this issue persists for us and we have worked around it for the time being.

**Comment by sonals-amazon** [comment]
@vishnubc If you are using navigation actions then the workaround mentioned above by @Dhairyasarous is the only way. We do have an internal feature request for providing an out of the box solution but it is not prioritized yet.

@skined90 We did receive your request internally and were able to resolve it.

**Comment by skined90** [comment]
@sonals-amazon We received this email:

> Hello,
 
You are receiving this messaging because your account has used QuickSight's GetDashboardEmbedUrl, GetSessionEmbedUrl, GenerateEmbedUrlForRegisteredUser, or GenerateEmbedUrlForAnonymousUser API in the last 180 days.
 
To further enhance the security posture of the embedded URLs generated by QuickSight, we will be updating them to be strictly one-time consumption-only on June 30, 2023. After this change, the embedded URLs returned by the APIs will expire after the first time they are accessed by an end-user. We recommend that you review your embedded QuickSight implementation to determine if there are any impacts to your application, and make changes if necessary.
 
If you have any questions or concerns, please reach out to AWS Support [1].
 
[1] https://aws.amazon.com/support
 
Sincerely,
Amazon Web Services

Therefore, does it mean that the suggested workaround will not work anymore, without providing a proper and working solution?

**Comment by bwelkin** [comment]
As stated in the email `the embedded URLs returned by the APIs will expire after the first time they are accessed by an end-user`. However, the embedded session created after the first use of the URL will still remain valid for the [SessionLifetimeInMinutes](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GenerateEmbedUrlForRegisteredUser.html#QS-GenerateEmbedUrlForRegisteredUser-request-SessionLifetimeInMinutes) duration set while requesting this URL. Thus, navigating between dashboards with the above provided solution should not be affected.
