### ISSUE TITLE
Embedded Dashboard doesnt allow more than 2 levels of drill-down

### ISSUE THREAD

**Issue by vishnubc** [awslabs/amazon-quicksight-embedding-sdk#121]
While embedding dashboards on QuickSight, we are able to drill-down to one level.  However, when we try for a further level, QuickSight refuses to connect.  Please find the error screen shot.  The drill down works perfectly well on QuickSight and has this error only on the embedded version.  Is this a limitation or am I doing something wrong ?
![image](https://user-images.githubusercontent.com/16410288/178194983-8af48137-e1d2-4147-bd44-d8ee28835c48.png)

**Comment by skined90** [comment]
Hello, we faced exactly the same issue. 

More details here:
https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/118

**Comment by vishnubc** [comment]
Many thanks for the reference, @skined90. Will explore the suggestion extended by @Dhairyasarous. Were you able to resolve the issue or is this a limitation?

**Comment by bwelkin** [comment]
The issue is not within the scope of `amazon-quicksight-embedding-sdk` package's functionality. The QuickSight team will look into this. Please create a support ticket to the QuickSight team for tracking if the issue is still not resolved.
