### ISSUE TITLE
Print button disappears in embedded dashboards

### ISSUE THREAD

**Issue by bernhardboehm** [awslabs/amazon-quicksight-embedding-sdk#122]
We are embedding Quicksight dashboards into our application and all of a sudden the Print button (as well as the Undo/Redo buttons) started to only appear on the first dashboard view but when navigating to another dashboard using dashboard.navigateToDashboard(options); it disappears. The behaviour is the same regardless of which dashboard I view first. 
Does anybody experience the same or maybe even have a solution?

**Comment by jcardus** [comment]
Yes, same here!

**Comment by bwelkin** [comment]
Thank you for reporting the issue. We are working on it and will update the thread once we have a fix.

**Comment by bernhardboehm** [comment]
Hello Brian, is there any news on this issue with the print button?

**Comment by sonals-amazon** [comment]
Duplicate of https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/125 

Tracking in the other github issue and closing this one.
