### ISSUE TITLE
Specify themeId in embedDashboard options

### ISSUE THREAD

**Issue by bgdnp** [awslabs/amazon-quicksight-embedding-sdk#124]
Currently we have frontend application which shows different branding styles based on logged in user, and we would also like to show different styles for embedded dashboards. I saw that for QSearchBar there is themeId option, is it possible to do something similar with dashboard embedding. Or is there workaround (with parameters or similar) to dynamically determine which theme to display. Thank you

**Comment by bwelkin** [comment]
Thank you for this feature request. Adding the themeId in dashboard embedding is in our plans in upcoming releases.

**Comment by jiajing28** [comment]
You can use new theme methods in SDK v2.5.0 to set a theme on load or within the session. You can reference how to get started [here](https://docs.aws.amazon.com/quicksight/latest/user/embedding-runtime-theming.html).
