### ISSUE TITLE
printEnabled not working

### ISSUE THREAD

**Issue by jcardus** [awslabs/amazon-quicksight-embedding-sdk#125]
This option simply has no effect.

**Comment by jcardus** [comment]
https://community.amazonquicksight.com/t/print-button-disappears-in-embedded-dashboards/4669/4

**Comment by jcardus** [comment]
This is a serious bug happening in production for a long time and no one says anything...

**Comment by jcardus** [comment]
This is the error on the console:

TypeError: Cannot read properties of undefined (reading ‘resolveLayout’)
at embed-dashboard.bundle.2a05befc715f17322e16.38.js:2:553771
at new WrappedComponent (embedding.c5ee2933f650865e747b.38.js:2:4340941)
at Oo (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:602407)
at za (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:619976)
at bu (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:661060)
at Rs (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:650473)
at Os (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:650285)
at _s (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:647147)
at platform-vendors.bundle.34b506e85458c4e59846.38.js:2:597937
at t.unstable_runWithPriority (platform-vendors.bundle.34b506e85458c4e59846.38.js:2:70744

It also happens if you use the url directly, please check the attached image carefully, you’ll see the printEnabled=true removes the toolbar
![3fab03b29da7bb303fc3f9f8f2469dac5e30ea66_2_378x500](https://user-images.githubusercontent.com/31902485/183260062-fe0ca0d8-5924-43b4-86d2-a68723e433c1.jpeg)
.

**Comment by bwelkin** [comment]
@jcardus i tested on the developer portal similar to what you did above. When I append `&printEnabled=true` to the iframe src, print functionality becomes available

https://user-images.githubusercontent.com/86490263/183763192-056d2a82-1215-4738-9726-de3fae2781a9.mov

could you give more info on your set up? what region was this observed? when was this issue last observed? is the full embed url (including `code` parameter) on the browser address bar (cannot see in your screenshot)

**Comment by bernhardboehm** [comment]
I experience the same problem and opened issue #122 with the same topic. The difference to your video is that my embedded dashboard consists in multiple sheets and the print button is there on the first page view, but disappears after navigating to a second sheet.
The code we are using to switch between sheets looks something like this:
```
dashboardApp.dashboard.sheetPending = (sheetId !== undefined) && (sheetId !== ‘’);
dashboardApp.dashboardObject.navigateToDashboard({
dashboardId: dashboardId,
sheetId: ${dashboardId}_${sheetId},
printEnabled: true,
});
```

**Comment by sonals-amazon** [comment]
The fix for maintaining state for printEnabled state was released about 2 weeks back. So this behavior should be working now. Can you confirm?

On a side note - you can use [navigateToSheet](https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/ae9a3b5525ed57b3dd3a7aa4fda3753b31922ac7/README.md#step-8-navigate-to-sheet-optional) to navigate between sheets and maintain all the initial properties without having to specify them again in your options object.

**Comment by bernhardboehm** [comment]
@sonals-amazon Thank you. It's working now.
