### ISSUE TITLE
Calling embedSession back-to-back causes "start" request to return 403

### ISSUE THREAD

**Issue by ben-gryps** [awslabs/amazon-quicksight-embedding-sdk#127]
I have a react application which embeds a quicksight console session in a sub-route (url/analytics). I run into an issue when navigating away from the path then back, too quickly, (/analytics => /something-else => /analytics). The action causes a new request to `generateEmbedUrlForRegisteredUser` which succeeds and returns a url. My react code then receives the new url and calls `embedSession` to inject it into my embed container. In the background, a `/start` request is made and returns a 403 with an external aws link explaining the session has expired. Additionally, I get an error `Inconsistent AppType between server EMBEDDING and undefined` with nothing to follow. Third, the call injects a second iframe into my container. I implemented clearing children before the call, which helps, but does not solve the issue.

<img width="1704" alt="Screen Shot 2022-10-10 at 10 17 46 AM" src="https://user-images.githubusercontent.com/107715683/194912894-026b954a-26d0-4106-b9c1-50b86027ef8c.png">

I just found in your documentation, under 'Troubleshooting', these warnings:
```
1. Make sure the URL you provide in options is not encoded. You should avoid using an encoded URL because it breaks the authcode in the URL by changing it. Also, check that the URL sent in the response from the server side is not encoded.
2. The URL only works if it used with the authcode it came with. The URL and authcode need to be used together. They expire after five minutes, so it's worth checking that you're not troubleshooting an expired combination of URL and authcode.
```
These seem to be related to my issue, but I found that the url coming from my server is not encoded. When would the url and authcode not be used together?

What am I missing? Huge thanks in advance for some insight.

**Comment by chaudhariv** [comment]
If you are not manipulating the URL or authcode inside it via your code, then first point in your list of troubleshooting steps is not relevant. You should verify though.

In the navigation process, if the iframe is teared down, then you cannot use the same URL as the authcode (bearer token) in it might have expired by that time (2nd point in above list of troubleshooting in your description). So if you cannot avoid tearing down the iframe, new session needs to be created by generating a new URL. 

In network trace of browser, if you see that same URL is being sent multiple times to the server, then that might explain an error.

**Comment by ben-gryps** [comment]
Thanks @chaudhariv. I am coming to the same conclusion.
