### ISSUE TITLE
How to get user's action on dashboard, such as mouse hover's value, click event?

### ISSUE THREAD

**Issue by wanhengpeng** [awslabs/amazon-quicksight-embedding-sdk#128]
Hi team,
I embed the quicksight dashboard into my external react application, and i can use SDK action to get parameters when parameters is changed.
I would like to know if there is a way for me to access the data that the user clicked on? or user's mouse hover callback

**Comment by bwelkin** [comment]
It is not possible to get the data the user has the focus at the moment. We will tract this as a feature request. Thank you.
