### ISSUE TITLE
Can not get the latest state value in parametersChangeCallback--React

### ISSUE THREAD

**Issue by wanhengpeng** [awslabs/amazon-quicksight-embedding-sdk#129]
Can not get the latest state value in parametersChangeCallback, when I get the React state value in parametersChangeCallback, it always is the init value

**Comment by wanhengpeng** [comment]
Swith to react class component, I can get the latest state, but cannot  get the latest state  use useState hook......

**Comment by bwelkin** [comment]
This seems to be an implementation issue. Could you please share relevant parts of your component code?

**Comment by wanhengpeng** [comment]
![image](https://user-images.githubusercontent.com/115466140/200454067-663ab206-9648-463f-b356-a5b3f81d52a7.png)
![image](https://user-images.githubusercontent.com/115466140/200453693-9947a834-6a81-4aec-9960-c1ebcb213953.png)
this is my parameterchangecallback, and I use state hooks to set value for chipdata， and below  is my effect hooks
![image](https://user-images.githubusercontent.com/115466140/200454018-10afe399-2d69-4b71-b9de-65c442b020a0.png)

**Comment by bwelkin** [comment]
You are changing `statusNew` property, but on parameters change callback, you are looking into `status` property. What is the name of the parameter in your analysis?

**Comment by sonals-amazon** [comment]
Closing. Not heard back from @wanhengpeng
