### ISSUE TITLE
 Programmatic Creation of Analyses and Sheets

### ISSUE THREAD

**Issue by thecodersourabh** [awslabs/amazon-quicksight-embedding-sdk#131]
I have visual data available to bind in the sheet for example (positions and types of visuals with source data) and I want to update the analysis with my updated sheets programmatically. 
Here are a few things I’d like to accomplish by programmatically creating analyses:

- Eliminate Manual Work: Creating Quicksight reports involves a lot of repetitive click-and-drag work. It would be more efficient to replace this with code.
- Improve Re-usability: Re-using content in Quicksight is a very click intensive manual process. Code is easier to reuse for similar work.
- Improve Precision: Click-intensive manual processes are naturally error prone. Giving users the ability to script out analysis creation reduces the potential for error.

Thanks in advance!

**Comment by sonals-amazon** [comment]
Hi,

Thanks for reaching out. Please use [quicksight community](https://community.amazonquicksight.com/) for questions or feature requests that are not related to QuickSight Embedding. We use this forum mainly for bugs in the embedding SDK.

You can also create a AWS Support ticket through your AWS account for other QuickSight issues.
