### ISSUE TITLE
errorCallback isn't fired in case of 403 happens

### ISSUE THREAD

**Issue by dil-btarkovacs** [awslabs/amazon-quicksight-embedding-sdk#135]
**Reproduce steps:**
1. get QS embedding URL: `qsURL`
2. embedd the iframe the following way: 
```
QuicksightEmbedding.embedDashboard({ 
    url: qsURL, 
    container: myContainer,
    // [...]
    loadCallback: () => { console.log('loaded'); },
    errorCallback: () => { console.log('error'); }
});
```
3. _// Iframe loads correctly, loadCallback is fired_
4. Destroy the container (so the iframe gets destroyed too)
5. Create a new Container element (as myContainer)
6. Try to embedd the iframe the same way as in step 2.

**Expected result:**
_I assume that we can't use the same URL more than once,_ so the iframe shouldn't load,
however **the errorCallback should be fired.**

**Actual result:**
Iframe doesn't load, and neither the errorCallback, nor the loadCallback gets fired.
Meanwhile 2 error appears in the browser's dev toolbar:
_Failed to load resource: the server responded with a status of 403 ()_
and
_embedding.dd[...]cf.38.js:formatted:117048 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document._
In the iframe, an error page appears with the text: 
_Embedding failed because of invalid URL or authorization code. Both of these must be valid and the authorization code must not be expired for embedding to work._

(I guess, the result would be the same if I tried to use the qsURL after its token was expired).

Assume that instead of showing the QS's Error page to the user, we want to automatically handle the error by getting a new URL and load that one.
As per the iframe doesn't have the same origin as the parent window, it's impossible to capture and handle this kind of errors.

**Comment by sonals-amazon** [comment]
Hello, sorry for such a delayed response. It is correct that same url cannot be used twice or the token expired. We are investigating why the error callback does not work for this error. We will post an update on it once we know the issue or have a fix.

**Comment by sonals-amazon** [comment]
We have taken this as a feature request as it is not supported yet.

**Comment by kuehnmic** [comment]
Closing this in lieu of https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/164
