### ISSUE TITLE
Unspecified dependency on uuid in v2.0.0

### ISSUE THREAD

**Issue by scarytom** [awslabs/amazon-quicksight-embedding-sdk#139]
After upgrading to the newly released v2.0.0 of this lib, our build is failing with the following output:

```
The required JS dependency "uuid" is not available, it was required by "node_modules/amazon-quicksight-embedding-sdk/dist/createEmbeddingContext.js".
```

It appears that amazon-quicksight-embedding-sdk now has a runtime dependency on the uuid package, but this is only specified as a dev dependency in package.json

**Comment by bwelkin** [comment]
Thank you for reporting this. We will look into the issue.

**Comment by bwelkin** [comment]
Patch is released. Once again, thank you for reporting this.
