### ISSUE TITLE
Dashboard not working with v2 sdk

### ISSUE THREAD

**Issue by grahamcarlyle** [awslabs/amazon-quicksight-embedding-sdk#140]
I tried switching from a working embedded dashboard using the 1.20.1 sdk to use the new 2.0.1 sdk but the dashboard fails to completely render (some of the menus appear but not the sheet contents) and I get multiple errors in the browser.

e.g. in the browser (up to date chrome and firefox)

error message: 
`"Could not get json from element: page-config"`
from platform-libs.bundle.2677a5cb271e2ffed854.39.js:2 getJSONFromElement

`Exception: embeddingControl.cf5a7a64f29fb881a868.39.js:2 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage' 
`

Also source maps are not working as the hosting domain is not resolving
`DevTools failed to load source map: Could not load content for https://sourcemaps.prod.us-east-1.quicksight.aws.a2z.com/charting/1.0.13932.0/esm/252.bundle.f40e4d4f02a96d99.2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
`

**Comment by bwelkin** [comment]
Could you please provide some more information about your setup? Do you see any failures in the network tab?

**Comment by grahamcarlyle** [comment]
I don't see any failures in the network tab, lots of resources are downloaded successfully including the iframe src. 

I can see 2 iframe elements mounted in the DOM. One iframe is mounted within the container specified in the embedDashboard call, and the other iframe is mounted under the body element. The first iframe has a div with id "page-config" with what looks like json as content, whereas the 2nd iframe has a script tag also with an id "page-config" but it is empty.

The site is built using the clojurescript shadow-cljs tool, which compiles to js. The v1.20.1sdk worked fine with it. I've also tried including the sdk via a script tag e.g. `<script src="https://unpkg.com/amazon-quicksight-embedding-sdk@2.0.1...">` but that fails in the same way

**Comment by bwelkin** [comment]
Thank you for the additional info.

I have been testing locally and `"Could not get json from element: page-config"` does not seem to cause any issue. We are working on eliminating that error message.

I am trying to repro the issue with `Invalid target origin ''` but I am not able to so far. The value is populated using `window.document.referrer`. In iframes, it's value is it's parent's `window.location.href`. (ref: https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer)

I am not sure under what circumstances it would become `''` for the second iframe.

I assume your page does not explicitly set referrerPolicy on iframe elements.
(ref: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/referrerPolicy)

Does your page enforce any referrer policy in the header?
(ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)

Do you use `resizeHeightOnSizeChangedEvent` property? If so, does setting it `false` and specifying an explicit `height` value help resolve rendering the sheet contents?

**Comment by grahamcarlyle** [comment]
Setting the height to an explicit pixel size rather than either not setting it or setting it to "100%" causes the dashboard to render as expected now. The `resizeHeightOnSizeChangedEvent` property wasn't being set.

Removing the `"same-origin"` referrer policy does stop the exceptions `Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage' `

**Comment by d-koppenhagen** [comment]
Hey, we have the same problem in our project. Embedding will not work and an error from the embedded scripts loaded is shown in the logs:

![Bildschirm­foto 2023-03-17 um 11 02 20](https://user-images.githubusercontent.com/4279702/225873958-c93623ac-7f4c-4372-9f45-0b5b5c46ea50.png)

**Comment by d-koppenhagen** [comment]
Okay, I will try this out. But as the SDK will create the iFrame, I can only set the referrer in the `<head>` of the document as a `<meta>`.

Generally it would be better to have an option using the SDK to pass the value to be applied [directly on the iFrame](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#integration_with_html) wouldn't it? 

As the referrer policy should only be used for one visual or dashboard.

**Comment by scarytom** [comment]
@d-koppenhagen the purpose of setting a referrer-policy is to prevent information being leaked to third parties via the Referer header.  For this reason, it is usual to set the policy for the widest scope, not the narrowest.  This typically means setting the Referrer-Policy header, which covers the entire page, or failing that using a meta in the head as you describe.  I'm not sure why you would choose to set it on the iframe directly.

**Comment by d-koppenhagen** [comment]
I generally agree: it's a good idea to use the widest scope.
But the need to set the referrer to a specific value to get the embedding working for a single visual can have side-effects for other elements on the page that may should use a different referrer policy. In this cases, one I want to add a QS visual on my page causes I have to explicitly set the refferer for all other page elements to a different value explicitly as the document must be set to `strict-origin-when-cross-origin`.

It could be the intention to use another policy for the whole document but not the embedded visuals coming from Quicksight. That's the reason, why it would be good to be able to explicitly set the referrer for the iFrame by having a config option.
Or even better in my opinion: when the SDK by itself already creates the iFrame and we nee the referrer for only this specific value to be set, why not directly adding it to the iFrame?

**Comment by d-koppenhagen** [comment]
Meanwhile I tried adding the suggested change to define the referrer to my page (in the `<head>`) part:

```html
<meta name="referrer" content="strict-origin-when-cross-origin" />
```
When checking the Chrome network Tab, I can see, the policy is set for the requested JS resources. Unfortunately it still does not work.

Note: When I remove the explicitly defined `<meta>` for the Referrer,  the `strict-origin-when-cross-origin` is also used, as it's the default.

**Comment by d-koppenhagen** [comment]
A bit more context:

I am trying to use `embedVisual` to embed a single visual. As `frameOptions.url` I pass the URL for anonymous Dashboard/Visual access. Creating an iFrame without the SDK passing this URL, I am able to include the visual.
I would be very happy to use the SDK in the future as it gives me some more flexibility for making the embedded visuals responsive.

**Comment by d-koppenhagen** [comment]
Okay, I noticed, the error was coming from trying to hand-over a ID for the container that wasn't valid (I dynamically created the ID by using the visualId form the Visual. But this won't work as an ID in HTML must start with a letter). However, the error from QS was not pretty easily understandable so I found my problem just now. (Probably an error log like "Conatiner Element does not exist in the DOM" or something similar would help for the future :)

After fixing my Issue with the `id`, I can confirm that the embedding with the referrer set to `strict-origin-when-cross-origin` (default). works.

**Comment by grahamcarlyle** [comment]
> v2.0 started using `window.document.referrer`, and it requires the default `strict-origin-when-cross-origin` Referrer-Policy. As a first step, we will update the README to reflect this behavior change. We will also look into if we can ease this requirement.

Should this issue be closed given the README has not been updated? as another developer may run into this issue?

**Comment by bwelkin** [comment]
This is no longer an issue in the version 2.1+.
