### ISSUE TITLE
enabled withIframePlaceholder flag on v2 SDK violates style-src CSP 

### ISSUE THREAD

**Issue by grahamcarlyle** [awslabs/amazon-quicksight-embedding-sdk#144]
The new v2 sdk violates the `require-trusted-types-for` CSP rule when I enable the `withIframePlaceholder`. I think this is because the code is setting innerHTML from an un-sanitised string.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for

**Comment by bwelkin** [comment]
Thank you for reporting the issue. We will look into it.

**Comment by bwelkin** [comment]
Could you please try `v2.0.3`? It no longer uses `element.innerHTML`

**Comment by grahamcarlyle** [comment]
This fixes the issue for me thanks

**Comment by grahamcarlyle** [comment]
I'm sorry but I spoke too soon, as the original CSP issue has been fixed, but now we get this CSP error 

`
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-exO902wtjEsWIT6+IERt+ipm9KD4hz4qxLQsJobAZaQ='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
`

I can't easily identify the code in the sdk that causes this because of the other issue #134 that i raised about source maps not working, but I think it is this line https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/84836765c9e803c570ab54d266ba6d8b1b9370e8/src/commons/createIframe.ts#L5

**Comment by bwelkin** [comment]
We are looking into this new issue also. Thank you.

**Comment by bwelkin** [comment]
style-src CSP violation should no longer be an issue in the version 2.1+
