### ISSUE TITLE
onMessage 'CONTENT_LOADED' is not received on dashboards with hidden visuals

### ISSUE THREAD

**Issue by nabilarbouz** [awslabs/amazon-quicksight-embedding-sdk#145]
It looks like dashboards published with templates/analyses in the free-form layout with hidden visuals based on rules do not allow the `CONTENT_LOADED` event to get to the `onMessage` function in the `contentOptions`. After removing the hidden visuals from the analysis and re-publishing the dashboard, the `CONTENT_LOADED` case in `onMessage` began activating as expected.

**Comment by bwelkin** [comment]
Thank you for reporting this issue. We are looking into it.

**Comment by robertkossendey** [comment]
Any updates on this? 

It has been a reported issue for more than half a year...

**Comment by bwelkin** [comment]
We have identified the issue and have been working on the fix. 

Meanwhile, would it be possible for you to open a technical AWS Customer support case https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

**Comment by robertkossendey** [comment]
@bwelkin we created a ticket that has been closed for 4 months, should we open up another one?

**Comment by bwelkin** [comment]
Yes, please open another one and specify it is QuickSight Embedding SDK related.

**Comment by robertkossendey** [comment]
I think this can be closed, as it is working now :) Thank you!
