### ISSUE TITLE
Invalid dashboard experience url - extractDashboardExperienceFromUrl

### ISSUE THREAD

**Issue by alanionita** [awslabs/amazon-quicksight-embedding-sdk#147]
Facing an issue where locally the embedding works but when deploy we're receiving an `Invalid dashboard experience url`. 

Tracking it down to `extractDashboardExperienceFromUrl` in `amazon-quicksight-embedding-sdk/dist/experiences/dashboard/createDashboardFrame.js` this logic seems a bit obtuse. 

`/^https:\/\/[^/]+\/embed\/[^/]+\/dashboards\/([\w-]+)(\?|$)/i`

If we run this regex manually on the embed url we get 1 match. 

`extractDashboardExperienceFromUrl()` does an early exist if there are less than 3 matches.

Can someone from the team add a bit more context on this error?

Other:
- config is correct as per docs
- users have correct permissions
- domain is included in the AllowedDomains scoping

**Comment by bwelkin** [comment]
The expected dashboard url pattern is: `protocolPart` + `quickSightDomain` + `"embed"` + `guid` + `"dashboards"` + `dashboardId`

Does the embed url you use in prod follow this pattern? If not, could you please share the pattern you have (please make sure not to share any private info, such as dashboardId, accountId, etc.) and please share how you obtained this url?

**Comment by bwelkin** [comment]
Some more details on the expected values for the url parts I shared above:

* `protocolPart` is `https://`
* `quickSightDomain` should match `regionName` + `".quicksight.aws.amazon.com"`
* `guid` strictly matches `[0-9a-f]{32}`
* `dashboardId` is usually in the form of `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}` when auto-generated. However, it is only required to match  `[\w\-]+` when it is customer generated ([reference](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisteredUserDashboardEmbeddingConfiguration.html#QS-Type-RegisteredUserDashboardEmbeddingConfiguration-InitialDashboardId)) 

Here is an example of a dashboard embed url
```
https://us-east-1.quicksight.aws.amazon.com/embed/0123456789abcdf0123456789abcdf/dashboards/12345678-1234-1234-1234-123456789abc?code=...
```
