### ISSUE TITLE
Missing events on load actions OR possibility to set a custom load screen 

### ISSUE THREAD

**Issue by jeroenmeulendijks** [awslabs/amazon-quicksight-embedding-sdk#148]
I guess this is a feature request but in (at least) 2 use-cases I'm missing events to correctly handle it in our webpage.

We hide the whole QuickSight iFrame during the load of a dashboard because the theming of the load screen is not at all matching the theme of our webpage. So if we should show the iFrame on that moment it looks really bad.

This works fine for the first load of a dashboard but cannot work in the following use-cases (I guess there could be more, but haven't encountered them):
- When using the `navigateToDashboard` function the iFrame loads a new dashboard and druing this load the iFrame is mostly white
- With the Bookmarks feature enabled you can switch between bookmarks. When you click a bookmark you see the same white iFrame while the bookmark is being loaded.

Too fix this I see 2 possible fixes:
- The QuickSight library should emit events the moment a new dashboard/bookmark is starting to load and the loaded event should be emitted the moment the dashboard/bookmark is loaded (Or any other content)
- Next to `withIframePlaceholder` we should have an option to specify which component is shown the moment QuickSight is loading a dashboard/bookmark (or anything else)

Personally I prefer option 2 because than we can specify what the iFrame should display the moment something gets loaded and maybe I could even remove our 'workaround' to not show the iFrame when we load the initial dashboard. But it does mean that the library should use this component everytime it is loading something (instead of the current white screen)

**Comment by jeroenmeulendijks** [comment]
Hi @sonals-amazon,

As suggested I created ticket: 12802860291 (Which also links to this issue) and added a screen capture of what I see.

Thanks for the support.

**Comment by sonals-amazon** [comment]
Closing this as we did receive the ticket mentioned above. We will use the ticket for any further communication. Thanks!
