### ISSUE TITLE
case 'ERROR_OCCURRED' doesn't happen when anonymous url expires 401

### ISSUE THREAD

**Issue by evertondanilo** [awslabs/amazon-quicksight-embedding-sdk#150]
**_Test scenario:_**
- Open an embedded dashboard with a valid anonymous URL
- wait until the URL expires
- try to use the report

According to the docs, I should get a message in the `onMessage` method with the event name `ERROR_OCCURRED`.

However, the onMessage method is not triggered.

In the network, I can see many 401 failures in the QS requests but they don't trigger the SDK onMessage method.

**Comment by kuehnmic** [comment]
This is a duplicate of https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/150
