### ISSUE TITLE
Sheet width scaling issues

### ISSUE THREAD

**Issue by ahwitz** [awslabs/amazon-quicksight-embedding-sdk#157]
This has been hard to describe internally, so please ask for clarification if any of this doesn't make sense:

- We have a multi-sheet dashboard.
- In that dashboard, there's a sheet with a three-column table, approximately ~1000px width.
- The sheet has three filters above it that take up <1000px.
- We're trying to lay it out responsively.

We've found the following issues with the three layout setting options:

- If we use "Classic", it seems to base the size of the visuals off the window size, rather than the wrapping iframe size. If the iframe wrapper is set to `min-width: 1200px` but our window is ~800px wide, the filters are hidden and can't be used, despite the iframe have enough space and the page being scrollable.
- If we use either the "Tiled" or "Freeform" layouts, at widths greater than the width of the table, the table scales to maintain the same proportional amount of whitespace, which means that at smaller window widths, the text becomes illegibly small.
- If we use either the "Tiled" or "Freeform" layouts at "optimized for 1024px", when we make the window wider, the text becomes humongous and wastes too much space.

I think what we're looking for is something along the lines of [fitToIframeWidth](https://github.com/awslabs/amazon-quicksight-embedding-sdk#-fittoiframewidth-boolean-optional-defaulttrue), but for dashboards. The succinct description would be "make a sheet responsively take up the full width of the iframe without hiding any components, but with a `max-width` setting."

 Is there a combination of settings, whether in QuickSight or in the SDK, that'll allow us to achieve that?

**Comment by bwelkin** [comment]
Could you please clarify the classic layout case?

I set the container element's `min-width` as `1200px`. (did not set `frameOptions.width`, thus, it remained as `100%` as default value for iframe element's width). Looks like:
```
<div id="my-container" style="min-width: 1200px">
    <iframe src="TheEmbedUrlHere" width="100%" ... >...</iframe>
</div>
```
Below `1200px` browser window width, the contents of the iframe did not change its shape (chrome, firefox, safari).

**Comment by kuehnmic** [comment]
Brians response should suffice, but if you're still facing this problem please reach out to us at our [developer community](https://community.amazonquicksight.com/c/learning-center/developer/36/none).
