### ISSUE TITLE
Javascript error when calling `getSheetVisuals` after the user switches sheets

### ISSUE THREAD

**Issue by alvaroc1** [awslabs/amazon-quicksight-embedding-sdk#162]
Version: 2.3.0

```
...
{
  parameters: ...,
  async onMessage (message, experienceMetadata) {
    switch (message.eventName) {
      case 'SELECTED_SHEET_CHANGED': {
        await embeddedDashboard.getSheetVisuals(message.message.selectedSheet.SheetId))
...
```

<img width="825" alt="Screenshot 2023-08-14 at 7 26 47 PM" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/107395/ad49c9d1-5a17-4248-9386-e9755f884424">

**Comment by bwelkin** [comment]
Thank you for reporting the issue. We are looking into the issue. Meanwhile, could you please contact [AWS Customer Support](https://aws.amazon.com/contact-us/) so that a ticket can be created and assigned to the QuickSight team?

**Comment by bwelkin** [comment]
The fix is made on the QuickSight application. Calling `getSheetVisuals` upon sheet change now succeeds.
