### ISSUE TITLE
Incorrect types for addVisualActions - ActionOperations

### ISSUE THREAD

**Issue by alvaroc1** [awslabs/amazon-quicksight-embedding-sdk#163]
Version: 2.3.0

```ts
// matches documentation but rejected by types
const actionOperation = {CallbackOperation: {EmbeddingMessage: {}}}

// allowed by types, but rejected at runtime
const actionOperation = {
  EmbeddingMessage: {}
}
                  
const action = {
  CustomActionId: 'action-2',
  Name: 'Action 2',
  Trigger: 'DATA_POINT_MENU',
  Status: 'ENABLED',
  ActionOperations: [
     actionOperation
  ]
}
```
                  
Workaround that seems to work:
```ts
const actionOperation = ({CallbackOperation: {EmbeddingMessage: {}}}) as any
```

I am guessing that, on this file:
https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/master/src/types.ts#L194

```ts
export type ActionOperation = CallbackOperation;
```
should really be:
```ts
export type ActionOperation = {
  CallbackOperation: CallbackOperation;
}
```

Runtime error call:
<img width="830" alt="Screenshot 2023-08-14 at 7 54 47 PM" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/107395/8d3354c1-ea44-4fef-831f-7f98b9f3ee60">

**Comment by bwelkin** [comment]
Thank you for reporting the issue and providing detailed information. We are looking into it.

**Comment by bwelkin** [comment]
2.3.1 fixes the issue.
