### ISSUE TITLE
`navigateToDashboard` does not work with anonymousUser

### ISSUE THREAD

**Issue by d-koppenhagen** [awslabs/amazon-quicksight-embedding-sdk#166]
Hi,

I am using the amazon-quicksight-embedding-sdk to embed dashboards using an anonymous user. Doing so, my UI requests an `EmbedUrl` from my backend which is generated by using the [@aws-sdk/client-quicksight](https://www.npmjs.com/package/@aws-sdk/client-quicksight) library (`GenerateEmbedUrlForAnonymousUserCommand`).
This works quite good initially when creating the context and opening the dashboard in the iframe initially.
However, I want to switch to other dashboards I have, without the need to completely destroy the iframe and re-creating everything with a different dashboardId.
I tried to reach the goal with the `navigateToDashboard` function but it seems not to work:

![Bildschirmfoto 2023-09-21 um 16 28 29](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/4279702/2d6c4e7f-320a-41e7-adb7-f164fddb2a64)

I double-checked the dashboardId I was using and the id exists. Opening the other dashboard also works, when using the way initial way (get URL from Backend with anonymous embed url).

Here is my example code from my two wrapper functions for loading the dashboard initially and for switching the dashboard.

```ts
  async loadDashboard(
    dashboardId: string,
    parameters: Parameter[] = [],
    target: string,
  ): Promise<QS.QSE.DashboardFrame | undefined> {
    const dashboards = await api.getQuicksightDashboard(dashboardId)
    /*
    
    the response stored in `dashboards` looks like this:
    
    {
      "default": {
        "$metadata": { ... },
        "AnonymousUserArn": "arn:aws:quicksight:<region>:<account>:anonymousUser/default/<id1>",
        "EmbedUrl": "https://<region>.quicksight.aws.amazon.com/embed/<id2>/dashboards/<dashboardId1>?code=...",
        "RequestId": "<id3>",
        "Status": 200
      }
    }
    
    */
    const embeddingContext = await QS.createEmbeddingContext()
    return embeddingContext.embedDashboard(
      { url: dashboards.default.EmbedUrl, container: target },
      { parameters },
    )
  },
  async switchDashboard(
    frame: QS.QSE.DashboardFrame,
    dashboardId: string,
    parameters: Parameter[] = [],
  ) {
    return frame.navigateToDashboard("<dashboardId2>")
  }
```
Is there some other / better way to simply switch the dashboard when I already have an anonymous EmbedUrl?

**Comment by bwelkin** [comment]
First thing comes to mind is that you may not be authorizing the second dashboard: Have you added the second dashboard's ARN into the `AuthorizedResourceArns` property in the `GenerateEmbedUrlForAnonymousUser` request? Ref: https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GenerateEmbedUrlForAnonymousUser.html#QS-GenerateEmbedUrlForAnonymousUser-request-AuthorizedResourceArns

You may find a blogpost with an example similar to your case helpful: https://aws.amazon.com/blogs/business-intelligence/level-up-your-react-app-with-amazon-quicksight-how-to-embed-your-dashboard-for-anonymous-access/

Meanwhile, I will try to repro the issue.

**Comment by d-koppenhagen** [comment]
Thanks 🙏 @bwelkin for pointing me in the right direction. Indeed, the problem was, I had just requested the anonymous URL for a single ARN for the specific dashboard. This explains why it worked for my first request via my  bff, as the backend received just the single dashboard ID from the UI.
For some reason I thought, I need to have an anonymous URL for each dashboard, but the initially generated URL already is authorized to access all ARNs when created.
Thank you! We can close this issue.
