### ISSUE TITLE
embedDashboard no longer available, but docs reference it for Angular build

### ISSUE THREAD

**Issue by dcp3450** [awslabs/amazon-quicksight-embedding-sdk#169]
I have an angular app that's been running fine with quicksight. After a recent round of package updates build is failing with the error:

`Property 'embedDashboard' does not exist on type 'typeof import("amazon-quicksight-embedding-sdk")'.`

Unfortunately, the documentation doesn't seem to have any details on what the breaking change was and/or how to adjust for it. The AWS doc for this still shows the process that I used for our setup:

https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/embed-an-amazon-quicksight-dashboard-in-a-local-angular-application.html

Any guidance on addressing the issue? Thank you!

**Comment by dcp3450** [comment]
If anyone else has this issue I found the solution, for me anyway. What I had was:

```
import * as QuicksightEmbedding from 'amazon-quicksight-embedding-sdk';
...
QuicksightEmbedding.embedDashboard({
      url: embeddedURL,
      container: containerDiv,
      scrolling: 'yes',
      height: '100%',
      width: '100%'
    });
```

The `embedDashboard` was erroring as not part of the QuicksightEmbedding anymore. I switched it to:
```
    QuicksightEmbedding.createEmbeddingContext().then(e => {
      e.embedDashboard({
          url: embeddedURL,
          container: containerDiv,
          height: '100%',
          width: '100%'
        });
    });
```

And it started working again.

**Comment by bwelkin** [comment]
Looks like you were using the version `1.x` and moved to `2.x`

`2.x` requires you to create a context instance first and the context instance exposes the `embedDashboard` method. Your last example is correct. If called inside an `async` function, `await` syntax makes the code more readable.

```
const embeddingContext = await QuicksightEmbedding.createEmbeddingContext();
const embeddedDashboard = await embeddingContext. embedDashboard({
    url: embeddedURL,
    container: containerDiv,
    height: '100%',
    width: '100%'
});
```
