### ISSUE TITLE
When setting parameters, is there a limit to the number of array values that can be passed?

### ISSUE THREAD

**Issue by barnesm999** [awslabs/amazon-quicksight-embedding-sdk#172]
I have a use case where our QuickSight DataSet may contain ~15K unique values for a particular column.

We want to define a parameter and filter the dashboard using the parameter against the column. We want this parameter to support multi-select. The values of the parameter would be string (ids).

We are using the QuickSight embedding SDK and we will have a control on our web app which lets the user select from a tree of filter values. The values are hierarchically structured, so selecting a top level identifier will need to pass all descendant identifiers as well. This could potentially result in thousands of values which we want to filter again.

I want to confirm whether there is any limit either in the SDK, or enforced by backend QuickSight which would prevent us from passing all necessary values. i.e., could we pass 14999 of the 15000 values without issue?

Thank you.

**Comment by jonathanRinciari** [comment]
Hey @barnesm999, 

According to our public APIs the limit is 50000 values. I tested that it works successfully with 20000 so it should be fine for your use case. If there is anything else please reopen or create a new issue.

Thanks,
Jon
