### ISSUE TITLE
Embedding Error: Websocket onclose failed with code: 1006

### ISSUE THREAD

**Issue by tyyzqmf** [awslabs/amazon-quicksight-embedding-sdk#173]
There is already content in embedding div, but the page cannot be displayed.
<img width="1047" alt="截屏2023-10-28 12 43 54" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/18416040/50897676-6fb4-4461-932a-c0165e10f0b4">

console error: `Websocket onclose failed with code: 1006`
![截屏2023-10-27 17 55 05 (1)](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/18416040/b93cefe6-cf52-4774-8771-1a0808d93ab6)

**Solution: Rollback to v2.3.1**

Code in React:
```
const embedContainer = async () => {
    const embeddingContext = await createEmbeddingContext();
    switch (embedType) {
      case 'dashboard':
        await embeddingContext.embedDashboard({
          url: embedUrl,
          container: `#EmbedId`,
          resizeHeightOnSizeChangedEvent: true,
        });
        break;
      case 'visual':
        await embeddingContext.embedVisual({
          url: embedUrl,
          container: `#EmbedId`,
          resizeHeightOnSizeChangedEvent: true,
        });
        break;
      case 'console':
        await embeddingContext.embedConsole(
          {
            url: embedUrl,
            container: `#EmbedId`,
            resizeHeightOnSizeChangedEvent: true,
            height: '1000',
          },
          {
            locale: i18n.language,
          }
        );
        break;
      default:
        break;
    }
  };
```

**Comment by jonathanRinciari** [comment]
Hey @tyyzqmf,

Can you share the code that you are using to embed the dashboard when using v2.4.0.

Would it be possible for you to open a technical AWS Customer support case https://docs.aws.amazon.com/awssupport/latest/user/case-management.html so we can assist further.

Thanks,
Jon

**Comment by tyyzqmf** [comment]
> Hey @tyyzqmf,
> 
> Can you share the code that you are using to embed the dashboard when using v2.4.0. Additionally, the 3rd screenshot looks like an error from cloudformation. Are you able to confirm that it is related to Quicksight embedding?
> 
> Would it be possible for you to open a technical AWS Customer support case https://docs.aws.amazon.com/awssupport/latest/user/case-management.html so we can assist further.
> 
> Thanks, Jon

Sorry upload the error image. I had updated image and the code in React.

**Comment by jonathanRinciari** [comment]
It looks like this might be related to https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/170. Can you try explicitly set the height and width to 100% (behavior in v2.3.1). 

Thanks,
Jon

**Comment by tyyzqmf** [comment]
It's OK. Explicitly set the height / width to 100%.
