### ISSUE TITLE
Methods getVisualActions, addVisualActions don't working

### ISSUE THREAD

**Issue by NZhan94** [awslabs/amazon-quicksight-embedding-sdk#176]
Hello. I tried to use getVisualActions and addVisualActions methods as described in the documentation, but I always received errors getVisualActions is not a function 
<img width="1672" alt="Screenshot 2023-11-10 at 12 56 15" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/150597818/3a80b252-22a9-4232-b818-36b316a13013">
 (https://github.com/awslabs/amazon-quicksight-embedding-sdk#-addvisualactions-sheetid-string-visualid-string-actions-visualaction--promiseresponsemessage). Ok, then I added console.log with embeddedFrame 
<img width="1671" alt="Screenshot 2023-11-10 at 12 57 58" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/150597818/bb68c339-f97c-492b-868f-01c44091cd43">. As you can see, names of the methods here are not the same as in the documentation. Then I tried to use getActions and addActions methods instead of getVisualActions and addVisualActions methods, but there is another error.
<img width="1680" alt="Screenshot 2023-11-12 at 19 28 11" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/150597818/f8d90e0e-a5d2-4f6b-ab97-37f6b66ddeeb">

How can I use method addVisualActions in my project?

**Comment by bwelkin** [comment]
It looks like you are using `embedVisual` for visual embedding as your console.log shows `addActions` method.

The method for adding actions in visual embedding is `addActions` (not `addVisualActions`. it is for dashboard embedding)
https://github.com/awslabs/amazon-quicksight-embedding-sdk#-addactions-actions-visualaction--promiseresponsemessage

Similarly, the method for getting actions in visual embedding is `getActions`

Let us know if using these methods resolve your issue.

**Comment by NZhan94** [comment]
Thanks for answer, but I wrote that I tried to use addActions and getActions in last paragraph

**Comment by NZhan94** [comment]
1. I tried on v2.2.4 and v2.3.1.
2. I got this error, when I used addActions. Then I tried use getActions and got this error too.
3.  I add the same code and got Uncaught (in promise).
`const { createEmbeddingContext } = QuicksightEmbedding;

    const embeddingContext = await createEmbeddingContext();
    const contentOptions = {
      parameters,
      onMessage: async (messageEvent: any) => {
        if (messageEvent.eventName === 'CONTENT_LOADED') {
          this.isLoading$.next(false);
        }
      }
    };
    const frameOptions = {
      url,
      height: '100%',
      resizeHeightOnSizeChangedEvent: this.resizeHeightOnSizeChangedEvent,
      container: `#dashboard-${this.visualId}${this.localId}`
    };
    this.embeddedFrame = await embeddingContext.embedVisual(frameOptions, contentOptions);
`
this.embeddedFrame in console log
<img width="570" alt="Screenshot 2023-11-15 at 18 29 40" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/150597818/6e3c5071-52e6-4abd-bab8-efb4f4be2883">
4. I used embedVisual

**Comment by bwelkin** [comment]
The embedded content may not be ready when you call the `addActions` method.

Would calling the `addActions` in the CONTENT_LOADED if-block work for your use case?
