### ISSUE TITLE
resizeHeightOnSizeChangedEvent do not work properly in v2.4.0

### ISSUE THREAD

**Issue by mvazan** [awslabs/amazon-quicksight-embedding-sdk#177]
I noticed invalid behavior after upgrading to 2.4.0. I use `resizeHeightOnSizeChangedEvent` frame option. It works fine when I open any of the reports for the first time, but it looks like it is not working once I return to the report I already opened. I cannot reproduce the bug on 2.3.1.
 
<img width="1436" alt="Screenshot 2023-11-16 at 17 49 48" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/67419955/4eedcadf-69ff-4120-8681-0112becf25bb">

**Comment by jonathanRinciari** [comment]
Hey @mvazan,

Are you able to share the code you are using when you are using the embedding SDK? 

Thanks,
Jon

**Comment by bwelkin** [comment]
Could you also elaborate on what you mean with `once I return to the report I already opened`. Repro steps would be very helpful.

**Comment by mvazan** [comment]
I already shared information internally, as I cannot share the source code publicly due to the company's restrictions. `once I return to the report I already opened` means that a dashboard's height is set correctly when I access it the first time after the application starts (dashboard A). The height is not applied only when I switch to another dashboard (dashboard B) and then I open the previous dashboard again (dashboard A - that one on the attached screenshot)

**Comment by bwelkin** [comment]
Thank you. We are looking into the issue in the support ticket.

**Comment by sonals-amazon** [comment]
Closing in favor of support ticket

**Comment by mvazan** [comment]
The issue has been solved. Thank you.
