### ISSUE TITLE
setThemeOverride is to strict on color value expectation

### ISSUE THREAD

**Issue by jeroenmeulendijks** [awslabs/amazon-quicksight-embedding-sdk#179]
When trying to implement the `setThemeOverride` method to change the theme on a dashboard depending on the user configuration I ran into the error:
```
"String "#fcfcfc" at UIColorPalette.PrimaryBackground does not match pattern /^#[A-F0-9]{6}$/"
```

So I cannot use color codes like:
- #fff
- black

Because I use react with SASS, colors are converted to be compressed by default it means before applying them in the QuickSight function I have to convert names to a hex color but also 3 hex codes to 6 hex codes and everything needs to be uppercase or it will also be rejected.

Would be much easier if all variants would just be allowed.

**Comment by bwelkin** [comment]
Thank you for your feedback.

The embedding SDK accepts the public models for the QuickSight themes (see: https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UIColorPalette.html) as an input, thus, doesn't support named and shorthanded colors.

Please use a converter logic before passing the color code to the input object properties. I did a quick search and saw several npm packages that perform such conversion.

Let us know if you need further help.

**Comment by jeroenmeulendijks** [comment]
Did you also find one that could convert from color name (ex. black) to hex color code?
I only saw a list of color names to hex somewhere but I'm doubting if it a full list.

But if I inderstand your answer correctly there's no intention to support these different values (hex, lowercase, colornames) from the SDK directly? So now eveybody using them first has to convert from whatever they use into the acceptable values in QuickSight SDK.

**Comment by bwelkin** [comment]
There is a list on a w3c page: https://www.w3.org/wiki/CSS/Properties/color/keywords

We currently do not support any conversion/translation/transformation logic in embedding SDK.

There are some npm packages aiming to perform color name conversions but I haven't used any of them: https://www.npmjs.com/search?ranking=popularity&q=color%20name%20to%20hex

**Comment by sonals-amazon** [comment]
Added this as a enhancement request in our queue. Closing.
