### ISSUE TITLE
`dev` and `prod` npm scripts aren't working by default

### ISSUE THREAD

**Issue by mjgpy3** [awslabs/amazon-quicksight-embedding-sdk#18]
When I try to run `npm run dev` and `npm run prod` they fail with
``` shell
$ npm run dev

> amazon-quicksight-embedding-sdk@1.0.3 dev /home/michael/dev/github.com/mjgpy3/amazon-quicksight-embedding-sdk
> webpack --mode development ./dist/index.js --output ./dist/quicksight-embedding-js-sdk.js

/home/michael/dev/github.com/mjgpy3/amazon-quicksight-embedding-sdk/node_modules/webpack-cli/bin/config-yargs.js:114
                                        optionsSchema.definitions.output.properties.sourceMapFilename
                                                                         ^

TypeError: Cannot read property 'properties' of undefined
```

I was able to make it work by commenting out various `describe` properties in `config-yargs.js`.

More information:
 - Node 12.6.0
 - NPM 6.9.0

**Comment by chillozz** [comment]
Hello @mjgpy3 
You need to update webpack-cli to version: "^3.1.1" or later.

Commands to fix it:
npm uninstall webpack-cli
npm install webpack-cli --save-dev

But we need create pull request and update package.json
