### ISSUE TITLE
[Feature Request] Runtime filtering should be able to be enabled/disabled

### ISSUE THREAD

**Issue by Miguel-Henriques** [awslabs/amazon-quicksight-embedding-sdk#182]
The recently released ability to apply runtime filtering should be opt in, similarly to how it is done for bookmarks.

For our use case, the motivation lies in us not wanting to introduce further complexity to the consumption of these views, as we consider the default filters shipped with the dashboards to be sufficient.

![Screenshot 2023-12-01 at 13 47 18](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/49489051/4ddb88d2-6aad-45a0-80f9-0a0a9bfec11e)

**Comment by Allymonies** [comment]
The filter pane shown in the screenshot appears to be the ad hoc filtering pane, separate from runtime filtering, indicating the analysis was published with the "Enable ad hoc filtering" setting enabled under Advanced publish options. If you are able to re-publish the dashboard with that setting disabled, the filter pane should be disabled. If this does not resolve the issue, please let us know!

**Comment by Miguel-Henriques** [comment]
My mistake then, thanks for the quick response.
