### ISSUE TITLE
CommonJS warning in console

### ISSUE THREAD

**Issue by pacocsfs** [awslabs/amazon-quicksight-embedding-sdk#184]
Hi,

I upgraded amazon-quicksight-embedding-sdk to 2.5.0 version. I’m getting a warning saying my component depends on this package. CommonJS dependencies can cause optimization bailouts. I followed the steps in the README file to set it up. I’m using import not require. My understanding is from version 2.4 you started offering ESM. Am I missing something? Is there a way to fix/remove this warning?

I’m using:
Angular 17
Node 8.17.1

Thanks.

**Comment by sonals-amazon** [comment]
Can you please share what warning are you getting and also the code snippet where you are importing.

**Comment by kuehnmic** [comment]
We haven't heard back from you so we're going to close this now. If you are still facing the issue though, please reach out to us at our [developer community](https://community.amazonquicksight.com/c/learning-center/developer/36/none).
