### ISSUE TITLE
iFrame src url not getting updated on successful rendering

### ISSUE THREAD

**Issue by BhaskarChezhiyan** [awslabs/amazon-quicksight-embedding-sdk#185]
I get 403 when the same embed URL is reused in the existing session window. This happens due to stateful URL in the iFrame src. The URL is designed for single use, so AWS invalidates the state once it is consumed on the initial rendering. But the URL in iFrame is still holding the state.

When i try the same in a new tab. The URL is redirected and the query parameters are removed, the same is not happening in the embedded IFrame. 

This forces to regenerate a new URL every single time when the dashboard container is focused in the DOM.

Possible solution is to update the iFrame URL on successful rendering or move state out of URL to header

**Comment by sonals-amazon** [comment]
Can you share what kind of state parameters are you passing in the url? Do these need to be updated based on context of your page? If you are trying to set parameters can you do so by using ` setParameters` action on the sdk?

**Comment by kuehnmic** [comment]
We haven't heard back from you so we're going to close this now. If you are still facing the issue though, please reach out to us at our [developer community](https://community.amazonquicksight.com/c/learning-center/developer/36/none).
