### ISSUE TITLE
navigateToDashboard timed out

### ISSUE THREAD

**Issue by WindRider7** [awslabs/amazon-quicksight-embedding-sdk#197]
When using `embeddedDashboardExperience.navigateToDashboard(dashboardId, options);` I always receive an error  `NAVIGATE_TO_DASHBOARD timed out`

I am not sure if related but I have this printed in console sometimes: 

`Websocket onclose failed with code: 1006 reason: The connection was closed abnormally, e.g., without sending or receiving a Close control frame`

Do you know what can be the issue?

**Comment by kuehnmic** [comment]
Hi @WindRider7, please reach out to our developer community [here](https://community.amazonquicksight.com/c/learning-center/developer/36/none) .
