### ISSUE TITLE
onMessage not triggered

### ISSUE THREAD

**Issue by WindRider7** [awslabs/amazon-quicksight-embedding-sdk#198]
When using `const embeddedDashboardExperience = await embeddingContext.embedDashboard(frameOptions, contentOptions);`

```
    const contentOptions = {
      onMessage: async (messageEvent, experienceMetadata) => {
        switch (messageEvent.eventName) {
          case 'ERROR_OCCURRED': {
            console.log('Error occurred while rendering the experience. Error code:', messageEvent.message.errorCode);
            break;
          }
          case 'CONTENT_LOADED': {
            console.log('Content loaded', messageEvent);
            break;
          }
        }
      }
    };
```

`onMessage` never is never called back

I am not sure if related but I have this printed in console:

`Error handling response: Error: runtime/sendMessage: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by kuehnmic** [comment]
Hi @WindRider7, we would need to see more of your implementation to figure it out. Most importantly, how the contentOptions are being passed to the embeddedExperience and how that experience is being mounted/rendered. 

Please reach out on the developer community [here](https://community.amazonquicksight.com/c/learning-center/developer/36/none) where we have SA's working to help debug this type of issue.

**Comment by kratipefo** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickSight Dashboard Embed</title>

    
    
    <script src="https://unpkg.com/amazon-quicksight-embedding-sdk@2.10.0/dist/quicksight-embedding-js-sdk.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 

    <script type="text/javascript">
        
        async function getQuicksightEmbedUrl(dashboard_id, recordID, module) {
            try {
                // console.log("Fetching QuickSight Embed URL...");
                const proxyUrl = `https://uatrmbventures.pefrontoffice.com/qs_api_v2.php?dashboard_id=${dashboard_id}`;
                const response = await $.get(proxyUrl);
                if (!response || !response.EmbedUrl) throw new Error("Invalid QuickSight embed response");

                // console.log("Embed URL Retrieved:", response.EmbedUrl);
                return module === "PortfolioCompany" ? `${response.EmbedUrl}#p.pcId=${recordID}` : `${response.EmbedUrl}#p.fundId=${recordID}`;
            } catch (error) {
                // console.error("Error fetching QuickSight URL:", error);
                return null;
            }
        }

        async function embedDashboard() {
            
            if (!window.QuickSightEmbedding) {
                // console.error("QuickSightEmbedding SDK is not loaded!");
                return;
            }

            const { createEmbeddingContext } = QuickSightEmbedding;
            const dashboard_embed_url = await getQuicksightEmbedUrl("4dc203b8-f4d5-4241-ac1a-cd5a808a5b08", 111072, "PortfolioCompany");

            if (!dashboard_embed_url) {
                // console.error("Failed to retrieve a valid QuickSight Embed URL");
                return;
            }

            // console.log("Embedding QuickSight Dashboard...");
            const embeddingContext = await createEmbeddingContext();

            const frameOptions = {
                url: dashboard_embed_url,
                container: document.getElementById("experience-container"),
                height: "600px",
                resizeHeightOnSizeChangedEvent: true,
                onChange: (changeEvent, metadata) => {
                        console.log('Context received a change', changeEvent, metadata);
                    }
            };

            const contentOptions = {
                    parameters: [
                        {
                            Name: 'country',
                            Values: [
                                'United States'
                            ],
                        },
                        {
                            Name: 'states',
                            Values: [
                                'California',
                                'Washington'
                            ]
                        }
                    ],
                    locale: "en-US",
                    sheetOptions: {
                        initialSheetId: "4dc203b8-f4d5-4241-ac1a-cd5a808a5b08",
                        singleSheet: false,                        
                        emitSizeChangedEventOnSheetChange: true,
                    },
                    toolbarOptions: {
                        export: false,
                        undoRedo: false,
                        reset: false
                    },
                    attributionOptions: {
                        overlayContent: false,
                    },
                    onMessage: async (messageEvent, experienceMetadata) => {
                        switch (messageEvent.eventName) {
                            case 'CONTENT_LOADED': {
                                console.log("All visuals are loaded. The title of the document:", messageEvent.message.title);
                                break;
                            }
                            case 'ERROR_OCCURRED': {
                                console.log("Error occurred while rendering the experience. Error code:", messageEvent.message.errorCode);
                                break;
                            }
                            case 'PARAMETERS_CHANGED': {
                                console.log("Parameters changed. Changed parameters:", messageEvent.message.changedParameters);
                                break;
                            }
                            case 'SELECTED_SHEET_CHANGED': {
                                console.log("Selected sheet changed. Selected sheet:", messageEvent.message.selectedSheet);
                                break;
                            }
                            case 'SIZE_CHANGED': {
                                console.log("Size changed. New dimensions:", messageEvent.message);
                                break;
                            }
                            case 'MODAL_OPENED': {
                                window.scrollTo({
                                    top: 0 // iframe top position
                                });
                                break;
                            }
                        }
                    },
                };
                const embeddedDashboardExperience = await embeddingContext.embedDashboard(frameOptions, contentOptions);
        }

        window.onload = embedDashboard;
    </script>
</head>
<body>
    <div id="experience-container" style="width: 500px; height:500px;"></div> 
</body>
</html>

Here is my code contentOptions is never getting called
