### ISSUE TITLE
embed iframe with leading attribute set to lazy

### ISSUE THREAD

**Issue by etylsarin** [awslabs/amazon-quicksight-embedding-sdk#199]
Hi,

Is there any option how to make the embedded iframe to use lazy loading?
And if not, is there any plan to enable it?

Thank you,
Filip

**Comment by Allymonies** [comment]
Hello,

To help us better provide assistance, could you describe your use case for this request? The Embedding SDK does not currently support setting the lazy loading attribute on the embedding iframe but depending on use case there may be alternatives available.

Thanks,
Alyssa

**Comment by etylsarin** [comment]
> Hello,
> 
> 
> 
> To help us better provide assistance, could you describe your use case for this request? The Embedding SDK does not currently support setting the lazy loading attribute on the embedding iframe but depending on use case there may be alternatives available.
> 
> 
> 
> Thanks,
> 
> Alyssa

Hi Alyssa,
We would like to embed multiple QS iframes to our page, some of those would be below the fold by default. For those it would be great to lazy load for better performance of the whole page.
From my perspective it wouldn't be  any difficult to propagate this flag from a config to iframe props.

Thanks,
Filip

**Comment by Allymonies** [comment]
Because embed URLs are only valid for 5 minutes, it's unreliable to have an iframe be lazy loaded. Our recommendation for this use case is to wait to fetch an embed URL and call `embeddingContext.embedDashboard` until the desired point is scrolled into view if lazy loading is required.

**Comment by etylsarin** [comment]
Ok, makes sense. Thank you!
