### ISSUE TITLE
Opening a URL action in "Same Browser Tab" does not work

### ISSUE THREAD

**Issue by mjgpy3** [awslabs/amazon-quicksight-embedding-sdk#20]
When embedding a dashboard with URL actions that open in the same browser tab, the iframe gets hijacked with an iframe error. This was encountered in chrome.

Example URL action
![same-browser-setting](https://user-images.githubusercontent.com/1709849/61477379-2045aa80-a95d-11e9-89ba-78937857440c.PNG)

Example error
![iframe-error](https://user-images.githubusercontent.com/1709849/61477470-584ced80-a95d-11e9-82e1-ce8dd8c3e10e.PNG)

**Comment by cxiangna** [comment]
Yes, it is broken because iframe refuses to display the target url. We don't have control of the target web page. Please use New browser tab or New browser window in this case as a workaround.
