### ISSUE TITLE
package version alert

### ISSUE THREAD

**Issue by mahmoudkTSN** [awslabs/amazon-quicksight-embedding-sdk#200]
Hi Team, is there an alert when a new package is released? 

sometimes, newer packages have breaking changes, and I don't get notified of it. I tried watching your repo's releases on GitHub but I think it will not work since you don't add any release version there 
<img width="405" alt="Screenshot 2024-03-05 at 3 11 57 PM" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/99269763/95a53059-7c91-4b7e-b920-0f226d83e396">

**Comment by mSounakAZ** [comment]
You can check releases more easily on npm: https://www.npmjs.com/package/amazon-quicksight-embedding-sdk?activeTab=versions.

**Comment by kuehnmic** [comment]
You can monitor our changelog here as well: https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/master/CHANGELOG.md

Additionally, you can monitor all feature updates on the QS blog here: https://community.amazonquicksight.com/c/announcements/12/none
