### ISSUE TITLE
URIError while passing "[%]" as a parameter value

### ISSUE THREAD

**Issue by ddimegusew** [awslabs/amazon-quicksight-embedding-sdk#202]
When I pass "[%]" as a value on parameter, I get a response from library {success: true} but all parameters stop being applied, and  URIError  shown on console.
Its worked on version 2.3.1, but stopped working after updating to 2.6.0  

Error:
![image](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/163851198/8c3cf4dc-245d-40f1-9e35-c5ff53588474)

Example of passing parameter:
![image](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/163851198/85cae166-f9e8-4398-be31-679c4c979f84)

**Comment by ddimegusew** [comment]
Fixed by encoding parameter value before sending it to QS using [encodeURIComponent() ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

**Comment by kuehnmic** [comment]
As stated above, you just need to encode the string before sending it.
