### ISSUE TITLE
Sending an empty array in setParameters does not result in all values being unselected

### ISSUE THREAD

**Issue by mlndshh** [awslabs/amazon-quicksight-embedding-sdk#203]
Code to reproduce the issue:
```
 embed
  .setParameters([
    {
      Name: 'parameter_name',
      Values: [],
    },
  ])
  .then((res) => {
    console.log('RES', res);
  });
```

Running the code above leads to no changes in the parameter's values at all, but the response returned is still a success. This is a problem for us as we have multi-select dropdowns outside of the embed iframe controlling the values for the parameters. So when 1 or more options are selected, things work fine (and when they are unselected too). However, when the selections go from 1 selection to 0, nothing happens.

Expected behavior: when an empty array is passed as the `Values` for a parameter in `setParameter`, all options should now be unselected.

**Comment by Jomii** [comment]
Instead of an empty array you are supposed to pass a Select all value that is set for the parameter. 

Check step 7 of https://docs.aws.amazon.com/quicksight/latest/user/parameters-set-up.html

**Comment by kuehnmic** [comment]
As @Jomii mentioned, you'll need to pass [`ALL_VALUES`] to toggle the values in the way that you're looking for per https://docs.aws.amazon.com/quicksight/latest/user/parameters-set-up.html
