### ISSUE TITLE
Types are not installed in dist folder

### ISSUE THREAD

**Issue by hubaozhang2000** [awslabs/amazon-quicksight-embedding-sdk#204]
I incorporated amazon-quicksight-embedding-sdk in Angular 13 project.

After I installed the 
amazon-quicksight-embedding-sdk
package. The following files were not installed:

`types.js
types.d.ts
......`
When I reference some types, 

`import {
	DashboardContentOptions,
	EmbeddingContext,
  } from 'amazon-quicksight-embedding-sdk/dist/types';`

It gives me an error:

Cannot find module 'amazon-quicksight-embedding-sdk/dist/types' or its corresponding type declarations.

How do I install everything in amazon-quicksight-embedding-sdk/dist folder?

**Comment by kuehnmic** [comment]
Are you still facing this issue? Please check in at the developer corner [here](  https://community.amazonquicksight.com/c/learning-center/developer/36/none).
