### ISSUE TITLE
Feature request: way to respond to clearing parameter values

### ISSUE THREAD

**Issue by mjgpy3** [awslabs/amazon-quicksight-embedding-sdk#21]
It appears that any parameters I set are reset when the "Reset" button is clicked. This makes some sense, however, my external controls get out of date as illustrated here
![no-way-to-respond-to-parameter-clearing](https://user-images.githubusercontent.com/1709849/61481589-9c90bb80-a966-11e9-86c6-f2510f805618.gif)

Is there a way to respond to the reset in the parent page?

**Comment by apatlori** [comment]
This is a valid usecase. This problem can be solved by sending the parameter value back as a post message whenever it is changed so that you can update the controls on your page. We are tracking this issue on our end and will try to prioritize the issue

**Comment by mjgpy3** [comment]
Thanks @apatlori.

**Comment by joyarunraj** [comment]
We released a feature in November, for the host application to listen to parameter values change in dashboard embedding: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-9-setup-parameters-change-callback-optional

I believe the latest JS SDK release, should help resolve your issue. Feel free to reopen issue, if this feature is not working for you.

**Comment by rominasteinberg** [comment]
Hi! How can I see which of the parameters has change? I have several controls and I want to trigger something just if one of the parameters has changed. Thanks in advance.

**Comment by joyarunraj** [comment]
Hi @rominasteinberg we don't have a way currently for that. will take this in as a feature request. 

Meanwhile, you can however figure out which of the parameters have changed, by tracking current set of parameter values in your application, using https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-11-get-active-parameter-values-optional and on parameters change event, comparing it with previous set of parameters. I know this is not ideal solution. However, you can use this as a workaround, while we try to work on your request.

**Comment by rominasteinberg** [comment]
thanks @joyarunraj, it helps.
