### ISSUE TITLE
Namespace 'NodeJS' has no exported member 'Timeout'.

### ISSUE THREAD

**Issue by Tickets14** [awslabs/amazon-quicksight-embedding-sdk#212]
How do you fix this error:
```
Error: node_modules/amazon-quicksight-embedding-sdk/dist/index.d.ts:60:30 - error TS2694: Namespace 'NodeJS' has no exported member 'Timeout'.

60     timeoutInstance?: NodeJS.Timeout;
```
![image](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/53848311/1f9b5a21-af54-44eb-b2a2-7c0b4a8c9c4c)

Version:
Angular 14
amazon-quicksight-embedding-sdk: 2.6.0

**Comment by sakibhos-amazon** [comment]
Hello, it is possible you may be missing the necessary types package that is needed for this. Try installing the node types definition package: `npm install @types/node` (may need to adjust depending on your package manager).
