### ISSUE TITLE
The 'Generate PDF' option does not appear on all dashboards

### ISSUE THREAD

**Issue by emilMircea** [awslabs/amazon-quicksight-embedding-sdk#224]
## Expected Behavior

Each dashboard should have a 'Generate PDF' option available. 

## Actual Behavior

Of the two dashboards, one has the "Generate PDF" option available while the other one does not. 

![No Generate PDF Option Dashboard](https://github.com/user-attachments/assets/31a0a8dc-0418-44ef-b12a-a03e3b79ed94)

![with genereate pdf](https://github.com/user-attachments/assets/ebaba86a-92a1-463e-ace2-d840f5eac169)

## Frontend implementation using the Amazon QuickSight SDK. 

```tsx
const QuickSightEmbed: React.FC<QuickSightEmbedProps> = ({ embedURL }) => {
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const embedDashboard = async () => {

            const embeddingContext = await createEmbeddingContext();

            const frameOptions = {
                url: embedURL,
                container: containerRef.current,
                resizeHeightOnSizeChangedEvent: true,
            };

            const contentOptions = {
                locale: "en-US",
                toolbarOptions: {
                    export: true,
                    undoRedo: true,
                    reset: true,
                }
            };

            await embeddingContext.embedDashboard(frameOptions, contentOptions);
        };

        embedDashboard();
    }, [embedURL]);

    return <div className="quicksight-embed" ref={containerRef} />;
};

**Comment by lvrau-amzn** [comment]
I have a couple of questions for the dashboard that's missing the export to PDF button:
1. When publishing the dashboard, have you ensured that under the `Advanced publish options` that the `Enable PDF download` option is enabled? 
1. Does the embedded dashboard have a dataset with either RLS or CLS tags and is the embedded dashboard URL generated for anonymous users?

**Comment by emilMircea** [comment]
Thank you for the questions. Here are the answers.
1. The "Enable PDF download" option is enabled. 
2. The dataset is with RLS tags and the embedded dashboard URL is generated for anonymous users. 

![Enable PDF option enabled](https://github.com/user-attachments/assets/2da9bcab-c861-4c8a-8127-3ddb4d5b3517)

**Comment by lvrau-amzn** [comment]
From our end, we've confirmed that this is expected behavior where anonymous users with a dataset that has RLS will not show the "Generate PDF" button. We'll mark this issue as an enhancement and pick it up based on prioritization

**Comment by emilMircea** [comment]
Thanks a lot for the reply and for marking it as an enhancement. I will close the issue now. Have a nice day!
