### ISSUE TITLE
Unexpected Behavior in Shared Dashboard Views

### ISSUE THREAD

**Issue by bclements** [awslabs/amazon-quicksight-embedding-sdk#230]
**Issue Summary:**
The shared views functionality is not aligning with the documented behavior, leading to confusion and unintended outcomes when sharing dashboards.

**Documentation Reference:**
According to the documentation [here](https://docs.aws.amazon.com/quicksight/latest/user/share-dashboard-view.html), the expected behavior of shared views is described as follows:

> "When others access your view of the dashboard by using the link that you sent them, they see the dashboard exactly as it was when the link was created. They see any parameters, filters, or controls that you changed."

This implies that shared views function as permalinks, preserving the dashboard's state at the time the link is created. The recipient  should always see the dashboard exactly as it was when the link was generated, regardless of subsequent changes made to the original dashboard.

**Observed Behavior:**
The actual behavior deviates from this expectation in several ways:

1. Shared Link Updates Dynamically with Dashboard Changes:
- A dashboard view is shared via a link with specific filters, parameters, and settings.
- Initially, the recipient sees the correct view.
- However, if the original dashboard is modified (e.g., changes to filters or parameters), these updates are reflected for the recipient when they access the same shared link.

2. Pre-Access Changes Affect the Shared View:
- A dashboard view is created with specific filters, parameters, etc., and shared via a link.
- Before the recipient opens the link, modifications are made to the dashboard.
- When the recipient accesses the link, they see the modified view instead of the originally shared view.

3. Multi-Sheet Dashboard Behavior:
- A dashboard with multiple sheets (e.g., Sheet 1, Sheet 2, and Sheet 3) is used.
  - Filters, parameters, and settings are configured on Sheet 2, and a shared link is created.
  - Before the recipient accesses the link, the dashboard's focus is changed to Sheet 1.
  - When the recipient opens the link, they see Sheet 1 (the current focus) instead of Sheet 2 (the intended shared state).

**Impact:**
- This behavior undermines the purpose of shared views as static, unchanging.
- It appear to create a cooperative dashboard experience where modifications by the sharer impact the sharee, contrary to expectations.
- The current functionality limits our ability to share dashboards in a consistent and reliable way, which is critical for our use case.

**Expected Behavior:**
When a dashboard is shared via a link, the recipient should always see the exact state of the dashboard at the time the link was generated. This includes:

- Preserving the specific filters, parameters, and settings as they were when the link was created.
- Maintaining focus on the sheet that was active when the link was created, even if the dashboard has multiple sheets.
- Ensuring the view remains static and unaffected by any subsequent changes to the original dashboard.

**Request for Confirmation and Resolution:**
Please clarify whether this behavior is intended or a bug that needs addressing. If it is unintended, we kindly request that it be resolved to align with the documented behavior of shared views.

Thank you for investigating this issue and for your support in resolving it.

**Comment by huaraymo** [comment]
Resolved during customer call
