### ISSUE TITLE
Tree Map Numbers not shown in mobility and embedded for mobile handset

### ISSUE THREAD

**Issue by DDdanielagualtieri** [awslabs/amazon-quicksight-embedding-sdk#24]
Hi Guys,
when I try to display a tree map on mobile, both using the quicksight web browsing directly and using the embedded into portal I cannot see the data labels.
Please check the screenshots and let me know how to fix (whether possible) or give an ETA for this. We have customers (b2b) on this.
BR
Daniela
![Screenshot_20190730-094241_Chrome](https://user-images.githubusercontent.com/53429747/62111131-371ac400-b2b0-11e9-9e24-06bab720fc60.jpg)
![image](https://user-images.githubusercontent.com/53429747/62111450-da6bd900-b2b0-11e9-8c90-d33bb3e5745e.png)

**Comment by Dhairyasarous** [comment]
Can you verify if this is still an issue? We haven't been able to repro this with the latest release.
