### ISSUE TITLE
How to persist/get currently applied parameters? 

### ISSUE THREAD

**Issue by maskaravivek** [awslabs/amazon-quicksight-embedding-sdk#26]
I am building a Vue JS app which lists multiple dashboards and each dashboard has few common parameters. I am trying to persist the parameters across dashboards so that the user doesn't have to reselect/reenter the values. 

- Is there a way to get the currently applied parameters?
- Is there a way to persist parameters across dashboards?
- Is there a event that tells us about changes in parameters?

**Comment by mark-hayward** [comment]
I was trying to do the same thing. I contacted AWS Support and unfortunately it's not possible. 
We created a single dashboard with multiple sheets instead.

**Comment by cxiangna** [comment]
It's not possible at this moment. We are tracking this as a feature request on our side. Thank you for your feedback!

**Comment by romsaechoi** [comment]
Embedded dashboard now supports persistence on parameters, with `statePersistenceEnabled` field in API call.
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GetDashboardEmbedUrl.html

**Comment by joyarunraj** [comment]
Is there a way to get the currently applied parameters? Yes, you can use this method in latest JS SDK, to get currently active parameter values in dashboard: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-11-get-active-parameter-values-optional

Is there a way to persist parameters across dashboards? Possible with `statePersistenceEnabled` field in `GetDashboardEmbedUrl` API call.
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GetDashboardEmbedUrl.html

Is there a event that tells us about changes in parameters? Yes, you can use this method in latest JS SDK, to get callbacks on parameter changes: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-9-setup-parameters-change-callback-optional
