### ISSUE TITLE
ReferenceError: Can't find variable: embedDashboard

### ISSUE THREAD

**Issue by maugustyniak101** [awslabs/amazon-quicksight-embedding-sdk#27]
When I remove below url. 

<script src="https://unpkg.com/amazon-quicksight-embedding-sdk@1.0.3/dist/quicksight-embedding-js-sdk.min.js" />

error goes away but fails on unknown library obviously. That url loads just fine.

I tried 1.0.4, the same results.

**Comment by joyarunraj** [comment]
Its always advisable to use latest version of embedding JS SDK. Feel free to re-open this issue, if you are facing the same issue with latest version of JS SDK.
