### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by jcardus** [awslabs/amazon-quicksight-embedding-sdk#28]
I don't seem to get how we change the language of an embedded dahsboard. I don't see any option for that. 

I also switched in QuickSight the language of the user I'm using to get the authenticated url. But I still get english...

Please check the snapshots.

<img width="926" alt="Screenshot 2019-10-16 at 20 40 53" src="https://user-images.githubusercontent.com/31902485/66952963-81ad1080-f055-11e9-9312-47abd779482f.png">
<img width="964" alt="Screenshot 2019-10-16 at 20 36 46" src="https://user-images.githubusercontent.com/31902485/66952967-840f6a80-f055-11e9-8ac1-c62a85244c44.png">

**Comment by cxiangna** [comment]
This is supported in version 1.0.6.
