### ISSUE TITLE
How to call sdk values from HTML - parameter based update of dashboard.

### ISSUE THREAD

**Issue by sai7** [awslabs/amazon-quicksight-embedding-sdk#3]
Hi, 

I am following embedding the dashboard using HTML. 

By following the docs, how to achieve step number. 3 i.e., to get the reference for the dashboard like this `var dashboard = QuickSightEmbedding.embedDashboard(options);`.  via HTML?

**Comment by sai7** [comment]
Yes, @FrankChen1992 .

There is no **npm** setup in our application.
So, following this URL,
https://docs.aws.amazon.com/quicksight/latest/user/embedded-dashboards-example-html.html

I am getting an error at the line: `var dashboard = QuickSightEmbedding.embedDashboard(params);` as `**QuickSightEmbedding** is not defined`.

I am sure that using npm, we can _require QuickSightEmbedding_. But how to achieve the same in the above-referred example(**HTML**).

Please let me know if I am still not clear.

**Comment by FrankChen1992** [comment]
Hi sai7,

You'd need to include <script type="text/javascript" src="https://unpkg.com/amazon-quicksight-embedding-sdk@1.0.1/dist/quicksight-embedding-js-sdk.min.js"></script> on your page.

Let me know if it resolves your issue.

Thanks,

**Comment by sai7** [comment]
Hi @FrankChen1992 ,

Thanks for your QuickResponse. Yes, I have included **<script>** in my html head section.

But, I had to include this AWS SDK _<script>_  tag at the bottom of the <body> tag.

This helped me to call the SDK methods. 

Thank you very much.
