### ISSUE TITLE
Embedded dashboard - Analyze contributions option is not showing along with drill up & down

### ISSUE THREAD

**Issue by swathipothula20** [awslabs/amazon-quicksight-embedding-sdk#33]
Embedded quicksight into Using RubyGem-aws-sdk-quicksight   = 1.6.x version which is not showing option 'Analyze contributions' on right click of the the graph. this option i can see on 
on quick sight dashboard directly (not embedded) it works correctly.

Does quick sight SDK support this feature ? if it supports , what actually i missed

**Comment by aaditya-amazon** [comment]
Currently, QuickSight Embedding does not support this feature. Is this something you are still interested in? @swathipothula20

**Comment by bwelkin** [comment]
Resolving this issue as it is not within the scope of the `amazon-quicksight-embedding-sdk` package's functionality. The QuickSight team will look into this.
