### ISSUE TITLE
No filter on mobile

### ISSUE THREAD

**Issue by jcardus** [awslabs/amazon-quicksight-embedding-sdk#34]
On mobile the Filter option get's hidden and there's no way the user can filter any visual!

Please check the video.
[Screen Recording 2020-03-04 at 11.35.59.zip](https://github.com/awslabs/amazon-quicksight-embedding-sdk/files/4287059/Screen.Recording.2020-03-04.at.11.35.59.zip)

**Comment by jcardus** [comment]
25 days and no answer? I consider this a bug...

**Comment by jcardus** [comment]
Can you give me some feedback on this. I realize it only happens in portrait mode. 
I'm talking about uisng this sdk on a web page on a mobile device.

**Comment by Manuelacosta98** [comment]
Hi @jcardus i am not part of the library team but i think your question my be releaded to Analytics settings 

![image](https://user-images.githubusercontent.com/33484814/129122736-4d573e76-1d11-4e89-8894-8aea5064da1e.png)

**Comment by Dhairyasarous** [comment]
The latest changes seems to have fixed the issues. Can you verify if this is  still occurring for you?
