### ISSUE TITLE
Adding Turkish language support

### ISSUE THREAD

**Issue by mesutcakir** [awslabs/amazon-quicksight-embedding-sdk#36]
Turkish language support needs to be added.  I examined the source codes, but I could not see the language files.

**Comment by bwelkin** [comment]
Adding language support is not within the scope of this package. The language support is controlled by the QuickSight itself. See the full list of the languages supported by QuickSight at https://docs.aws.amazon.com/quicksight/latest/user/choosing-a-language-in-quicksight.html
Feel free to submit a `Turkish language support` request to QuickSight team.

`amazon-quicksight-embedding-sdk` will support any new language added to QuickSight without requiring any update.

`QuickSight` 'a ve  `amazon-quicksight-embedding-sdk`'e gösterdiğiniz ilgi için teşekkürler.
