### ISSUE TITLE
Error: can't find valid container

### ISSUE THREAD

**Issue by Orinameh** [awslabs/amazon-quicksight-embedding-sdk#38]
I seem to get this error `Error: can't find valid container` even when I pass the container in my options. What could be the issue? I am using React hooks btw.

**Comment by NikeyMice** [comment]
@Orinameh I am using React as well and used `createRef` to do this. when I set the container in the options, I set the container as `container: dashboardRef.current` and set `<div ref={dashboardRef} />` in the element I want the dashboard to display in and the error should go away.

**Comment by anthonysauer** [comment]
@NikeyMice Hi I'm a beginner to React and have tried your solution, but am still receiving the same error.

My code: (Apologies if things are not formatted well)

`const dashboardRef = React.createRef();

var options = {
    url: "https://XXXX",
    container: dashboardRef.current,
    scrolling: "no",
    height: "700px",
    width: "1000px",
    locale: "en-US",
    footerPaddingEnabled: true
};

const dashboard = QuickSightEmbedding.embedDashboard(options);

function dash() {
    return (
        <div ref={dashboardRef} content={dashboard} />
    );
}

export default dash;`

Using this, I still get Error: can't find valid container when creating `const dashboard`. Any help would be really appreciated!

**Comment by NikeyMice** [comment]
@anthonysauer Try setting it up like the following example:
```javascript
const Dash = () => {
    const dashboardRef = React.createRef();

    const embed = () => {
        const options = {
            url: "https://XXXX",
            container: dashboardRef.current,
            scrolling: "no",
            height: "700px",
            width: "1000px",
           locale: "en-US",
           footerPaddingEnabled: true
        };
       QuickSightEmbedding.embedDashboard(options)
    };

    React.useEffect(() => {
        embed();
    });

    return (
           <div ref={dashboardRef} />
    );
};

export default Dash;
```

**Comment by anthonysauer** [comment]
@NikeyMice That worked! Thank you so much for your help!
