### ISSUE TITLE
 This content cannot be displayed in a frame

### ISSUE THREAD

**Issue by ts-ankit** [awslabs/amazon-quicksight-embedding-sdk#39]
There are some issues in case of Internet explorer. Getting the below error when trying to in case of Internet Explorer:-

 This content cannot be displayed in a frame.

**Comment by joyarunraj** [comment]
Which version of IE are you testing in? Are you still facing this error? Also, make sure to whitelist your website domain in QuickSight: https://docs.aws.amazon.com/quicksight/latest/user/approve-domain-for-dashboard-embedding.html. And also, use the latest version of JS SDK for embedding purposes.

**Comment by aaditya-amazon** [comment]
Are you still facing this error? @ts-ankit
