### ISSUE TITLE
Support for browser through es6 imports

### ISSUE THREAD

**Issue by umbertoand** [awslabs/amazon-quicksight-embedding-sdk#4]
Would be great to make this available as a plain js es6 import so that the code can be used and encapsulated within a web-component.

**Comment by cxiangna** [comment]
Hi umbertoand,

I am not a web expert and I am not sure I fully understand what you requested. Can you give us more details about your use case, and point out what is preventing you from doing that?

We do provide the SDK as a node module: https://www.npmjs.com/package/amazon-quicksight-embedding-sdk, and there are ways to import node modules to your Front end project like this one: https://hackernoon.com/use-es6-javascript-syntax-require-import-etc-in-your-front-end-project-5eefcef745c2. Is this what you'd like to achieve?

Thank you for your valuable feedback!

**Comment by umbertoand** [comment]
Hi @cxiangna, yeah that's pretty much it - would just be nice if this was supported out of the box, without having to set up a bunch of build tooling.

**Comment by cxiangna** [comment]
Hi @umbertoand, correct me if I am wrong: According to my understanding, the bunch of build tooling you mentioned are for your project -- If you'd like to build your front-end project in a "modern" way, you'd have to use them. I don't see how Library providers can help you avoid using the building tools.

It will be great if you can tell us more about you project setup and how we can help. I think It might be much easier if you can name a Library you are using which already provides the consumption option you requested in this issue -- It will help us understand what we need to build exactly.

Thanks!

**Comment by comfytoday** [comment]
In VueJS, using 'require' works, but import doesn't:

`let QuickSightEmbedding = require("amazon-quicksight-embedding-sdk")`

Works as expected.

But...

`import QuickSightEmbedding from 'amazon-quicksight-embedding-sdk'`

Fails:

> TypeError: amazon_quicksight_embedding_sdk__WEBPACK_IMPORTED_MODULE_3___default.a is undefined

Is this expected, or do you have some advice for how the library should be imported?

**Comment by sheraz-sarwar** [comment]
@umbertoand @comfytoday You're able to do the following to import Quicksight functions using ES6+ syntax.

`import { embedDashboard } from 'amazon-quicksight-embedding-sdk';`

Alternatively, if you need the entire module, try this.

`import * as Quicksight from 'amazon-quicksight-embedding-sdk';`

Which would then allow you to do something like `Quicksight.embedDashboard()`.

**Comment by comfytoday** [comment]
Great, thank you! That's awesome.

Can you please put this in the README file/doco?

**Comment by sheraz-sarwar** [comment]
@comfytoday That's done, it might be one for @cxiangna to take a look at.

**Comment by cxiangna** [comment]
Thanks guys! The pull request has been merged.
