### ISSUE TITLE
Is it possible to link to a specific sheet with an AWS QuickSight embedded dashboard?

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/amazon-quicksight-embedding-sdk#40]
I know I'm able to pass specific parameters to control dashboard filters using options with the embedDashboard function as shown in the example below.

```
function embedDashboard() {
                var containerDiv = document.getElementById("dashboardContainer");
                var options = {
                    url: "https://us-east-1.quicksight.aws.amazon.com/sn/dashboards/dashboardId?isauthcode=true&identityprovider=quicksight&code=authcode",
                    container: containerDiv,
                    parameters: {
                        country: "United States"
                    },
                    scrolling: "no",
                    height: "700px",
                    width: "1000px"
                };
                dashboard = QuickSightEmbedding.embedDashboard(options);
            }
```

What I'm attempting to do is provide a link for a user to navigate to a specific sheet within an embedded dashboard. I could not find any reference to this pattern in the 'amazon-quicksight-embedding-sdk' documentation. I know for non-embedded dashboards you can navigate to a specific tab using the URL format *https://us-east-1.quicksight.aws.amazon.com/sn/dashboards/dashboardId/sheets/sheetId*, but I can't find how to control this with the embedding SDK.

Does anyone know if this is possible?

**Comment by lukec** [comment]
I wanted to do this too.  I just tried taking the result of the getDashboardEmbed API, and then added `/sheets/$SHEET_ID` at the end of the path, before the query string. It worked!

**Comment by joyarunraj** [comment]
This feature is now supported with latest JS SDK release v1.0.15: https://github.com/awslabs/amazon-quicksight-embedding-sdk#sheetid-element-optional
