### ISSUE TITLE
Feature request: Print/Export Report as on the Quicksight site

### ISSUE THREAD

**Issue by SaifElkholy-districtm** [awslabs/amazon-quicksight-embedding-sdk#41]
Hey,
I was looking into a way to get a screenshot of my embedded QS report in the same way that a user can do that on the quicksight website.

![image](https://user-images.githubusercontent.com/61166579/83268040-0f77df00-a193-11ea-80ca-9b836ddab783.png)

Can this be added to the library/what would need to be done?

Thanks!

**Comment by gblachonupg** [comment]
Hello,

We would love that too here !

**Comment by uusimaeki** [comment]
One more

**Comment by joyarunraj** [comment]
We have added print option via the https://github.com/awslabs/amazon-quicksight-embedding-sdk#printenabled-element-optional in latest version of embedding JS SDK.
