### ISSUE TITLE
using any string function in custom calculated flied not working in KPI Widgets

### ISSUE THREAD

**Issue by syedabidali** [awslabs/amazon-quicksight-embedding-sdk#43]
![image](https://user-images.githubusercontent.com/14038836/84568009-06436080-ad96-11ea-8eb6-35d8f2187c98.png)

![image](https://user-images.githubusercontent.com/14038836/84568017-0e9b9b80-ad96-11ea-8c49-542bfcd4a4df.png)

**Comment by joyarunraj** [comment]
Is this issue about QuickSight embedding, or you are facing this issue in QuickSight website?

**Comment by Dhairyasarous** [comment]
Looks unrelated to embedding.
