### ISSUE TITLE
looking for print/export to pdf option in embedded dashboard same as you have print option in quicksight UI

### ISSUE THREAD

**Issue by syedabidali** [awslabs/amazon-quicksight-embedding-sdk#45]
looking for print/export to pdf option in embedded dashboard same as you have print option in quicksight UI

**Comment by gblachonupg** [comment]
Hello,

We would love that too here !

**Comment by jcardus** [comment]
Hello, one more

**Comment by uusimaeki** [comment]
One more

**Comment by SaifElkholy-districtm** [comment]
One more :)

**Comment by pachae** [comment]
Hello, One More

**Comment by leovilla89** [comment]
Hi, one more!

**Comment by diemedina** [comment]
I need it too, thanks

**Comment by jredman-prev** [comment]
We would appreciate that feature as well!

**Comment by drfish** [comment]
Another!

**Comment by geoffmcqueen** [comment]
Adding another vote to this. Ideally it would be something we could call via JS rather than having it live inside the Embedded IFRAME so we could position the button in a way that doesn't compete with the very important reports real-estate.

**Comment by alexmcmanusgit** [comment]
One more! Please add this functionality

**Comment by stefan-ub** [comment]
Also in favor of this!

**Comment by Anis-Souayah** [comment]
me too

**Comment by mrdanieljcook** [comment]
+1 for this

**Comment by ashu2shin** [comment]
Would love that one.

**Comment by martinhadid** [comment]
I want this feature

**Comment by kareematqsaws** [comment]
Hi All, with the latest release as of Nov 20 (Version 1.0.12) you can enable print in the embedded dashboard via JS SDK. sample code: "printEnabled: true"

We have a JS SDK playground enabled for embedded analytics here: https://developer.quicksight.aws/embedSample/dashboard
Click on "How to customize it" which take you to the playground view where you can see the various JS SDK functions we support and see the code for them when you try out these functions.

**Comment by SaifElkholy-districtm** [comment]
Hey @kareematqsaws!
Thanks for adding this much requested feature.

However, this feature is now tied to the undo/redo & reset UI controls. Our use case requires that these 2 UI controls are not visible, but that the print option is visible.

Would it be possible to have this print option be an independent parameter (as is the case with the other 2 UI controls)?

Thanks!

**Comment by geoffmcqueen** [comment]
Echoing @SaifElkholy-districtm - thanks @kareematqsaws for adding this. Similarly in our use case, showing the undo/redo header isn't desirable. The ideal outcome would be the ability to initiate the print experience within the embed via JavaScript from outside the embed.

**Comment by joyarunraj** [comment]
We understand your pain point. We dont currently support print option isolated, with/without the navbar. However, I can see that this is a valid request. We are tracking this request on our end, and will try to prioritize this.

**Comment by aaditya-amazon** [comment]
In release **1.0.13**, we added `initiatePrint` function for printing a dashboard from parent website, without need for navbar print icon.

**Comment by RABilck** [comment]
One more, thanks for this report.

**Comment by jcardus** [comment]
it's available
