### ISSUE TITLE
Dashboard take too much time to load.

### ISSUE THREAD

**Issue by syedabidali** [awslabs/amazon-quicksight-embedding-sdk#46]
I have embedded Amazon QuickSight dashboard in my web application  But the problem assets in iframe is very heavy and it's very slow. I need to wait for 2 mins to get this loaded. And since embedded URL has been changed every time, it is not cached. I am using spice as well

Any help would be appreciated.

**Comment by AndrewCi** [comment]
Agreed.

**Comment by zzhengyi-amazon** [comment]
Hello,

Performance issue will be case by case. Could you contact AWS Support and cut a ticket to QuickSight Embedding team?  Thanks.
