### ISSUE TITLE
Feature Request: Support dashboard.getParameters()

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/amazon-quicksight-embedding-sdk#49]
Hello -

This is a feature request to support a dashboard.getParameters() function in addition to dashboard.setParameters().

This would allow apps to read the current state of the dashboard and support additional functionality.

Best,
Andrew

**Comment by stefan-ub** [comment]
We'd also like to have this feature.
We use multiple different dashboards that share controls. Switching between dashboards always resets those controls because we can't capture the current settings and pass them to the next dashboard.

**Comment by joyarunraj** [comment]
With the latest JS SDK release,  it is possible to get the active parameter values in an embedded dashboard. Please refer to this section of README, to learn further about this: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-11-get-active-parameter-values-optional
