### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by SagarSidhu** [awslabs/amazon-quicksight-embedding-sdk#50]
Seems this SDK does not support embedding in IE 11. 
The issue seems to be with some ES6 syntax. The compiled Quicksight package includes code which uses `class` , which is ES6 and not supported in IE. 
The issue seems to triggered in `/node_modules/amazon-quicksight-embedding-sdk/dist/EmbeddableObject.js` on ` line 184 col 1 in createIframe `

**Comment by samuelhwilliams** [comment]
Getting the same issue. :(

<img width="399" alt="Screen Shot 2020-09-02 at 13 34 38" src="https://user-images.githubusercontent.com/2920760/91981644-0e6dc500-ed21-11ea-92e5-0bf512ed0e51.png">

**Comment by nyctophiliacme** [comment]
I am also getting the same issue. Is there any work around for this?
![Screenshot (28)](https://user-images.githubusercontent.com/17355873/92415525-ef36c380-f176-11ea-9f13-61e061856b02.png)

**Comment by joyarunraj** [comment]
Thank you for bringing this issue to our attention. The IE11 embedding issue is resolved with the 1.0.11 release.
