### ISSUE TITLE
Feature Request: Support for landing on desired sheet-id directly rather than navigating to it after the dashboard is fully loaded

### ISSUE THREAD

**Issue by amit2555** [awslabs/amazon-quicksight-embedding-sdk#58]
Hi,

It would be really nice if the feature is added to landed on desired sheet-id directly rather than navigating to it after the dashboard is fully loaded. This would avoid unnecessary waiting.

While you are at it, can you also allow using sheet-name instead of sheet-id - its more user-friendly.

Thanks.
Amit

**Comment by sveisvei** [comment]
Same as https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/40
