### ISSUE TITLE
Cannot create data source because vpc connection is not shown

### ISSUE THREAD

**Issue by felipepulpo** [awslabs/amazon-quicksight-embedding-sdk#60]
Hello,

I want to connect to my database that is protected by a security group through a vpc connection.
Now CDK stopped allowing to create databases with the flag publicly accesible and no private subnets. We dont have private subnets so the only way is to create the databases as public accessibly. 
When I do this, quicksight selects the public network on data source creation and that way I cannot access it.

It looks like a bug in quicksight. Is it? Can this be solved? 

Thanks you very much

**Comment by joyarunraj** [comment]
Hi,

This is a SDK for helping with embedding QuickSight dashboards in customer's own website. We can help address issues and feature requests related to embedding and the embedding SDK, in this forum. For all other QuickSight issues, we recommend reaching out to QuickSight support through: https://aws.amazon.com/contact-us/
