### ISSUE TITLE
Feature Request: Invoke print via SDK from host

### ISSUE THREAD

**Issue by jwilko-accelo** [awslabs/amazon-quicksight-embedding-sdk#62]
The recent addition of the `printEnabled` option is greatly appreciated, thank you.  Unfortunately the real estate the button takes up on the screen and the forced coupling of the button to reset and/or undoRedo have meant that our implementation is unable to make use of this valuable feature.  

The ability to invoke the print functionality via an SDK function call would allow us to position and style the button to suit our UX, outside the embed iframe. 

I imaging the implementation could be similar to the way we are able to manipulate parameters from the host page. Something as simple as:

```
const dashboard = QuickSightEmbedding.embedDashboard(options);
...
// then in the host application print button onclick handler... 
dashboard.print();
```

**Comment by chaudharivijay** [comment]
We are currently working on this issue.

**Comment by joyarunraj** [comment]
with the latest JS SDK release v1.0.13, print can be initiated from parent website, via JS SDK, without need for a navbar icon: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-13-initiate-print-from-js-sdk-method
