### ISSUE TITLE
Feature Request: support `undoRedoDisabled` and `resetDisabled` options

### ISSUE THREAD

**Issue by hirouniverse** [awslabs/amazon-quicksight-embedding-sdk#65]
Currently, this SDK doesn't support to pass `undoRedoDisabled` and `resetDisabled` options to set them as URL query parameters.

If SDK supports this feature:

- frontend can control whether to display those options on the UI so that developer can control UX as much as possible.

Please kindly consider to include this feature.

Thank you so much for your great support to maintain this oss : )

**Comment by aaditya-amazon** [comment]
Latest SDK release 1.10.16 version has added these two options: `undoRedoDisabled` and `resetDisabled`

**Comment by HongKongDoll** [comment]
@aaditya-amazon where 1.10.16 ? just 1.0.17 founded

https://www.npmjs.com/package/amazon-quicksight-embedding-sdk

**Comment by HongKongDoll** [comment]
1.0.16 https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/master/CHANGELOG.md

- Adding undoRedoDisabled and resetDisabled flags to JS SDK
