### ISSUE TITLE
React application integrates with it, refused to connect

### ISSUE THREAD

**Issue by dongtong** [awslabs/amazon-quicksight-embedding-sdk#67]
![image](https://user-images.githubusercontent.com/319788/103212361-68d9f500-48bf-11eb-95d4-9c1000128cc1.png)

I had got correct embed url
```
{
  EmbedUrl: "https://us-west-2.quicksight.aws.amazon.com/embed/768d729352c54450a0866d2fdf882c9c/dashboards/254c2af1-2946-4506-8b9a-32a6b8204208?isauthcode=true&identityprovider=quicksight&code=AYABeFpGmEhiUX48cuYfJcG9qvAAAAABAAdhd3Mta21zAEthcm46YXdzOmttczp1cy13ZXN0LTI6OTAwNjQ5NDI3MTk2OmtleS9iYzAzMTYzMy0xYzJiLTRlMzEtYWM5ZC0yODQ2NDkwZjEyM2YAuAECAQB4a5Vy65_NRyq3IDuV8LaXpVn7UOrMGtsATSOtV23nDY..."
RequestId: "7ea58b39-d5fc-4947-8fdd-3e6f445903f0"
Status: 200
}
```

I could open `EmbedUrl` in a new tab, but it refused by aws.

**Comment by dongtong** [comment]
@Dhairyasarous Would you like to help figure out this? Thanks a lot!

1. I had added domain in QuickSight whitelist.
2. EmbedUrl was correct, I could open it in another browser without iframe. Access it directly in browser.
3. From Chrome network to see, I used amazon-quicksight-embedding-sdk to embed dashboard in iframe, iframe requests us-west-2 dashboard successfully, the HTTP is GET and code is 200, but there is no response in http request. It should be refused by quicksight dashboard. I am not sure why it is refused.

**Comment by miguelbogotanvc** [comment]
@dongtong Have you found a solution for this? This is also happening to my React App.

* I'm currently using the version: 1.0.12
* I can also open the `EmbedUrl` in a new tab and it works well.

Something to add it's that I'm also receiving this error message from the chrome dev tools.

![image](https://user-images.githubusercontent.com/71340917/105534993-49669a00-5cbc-11eb-914a-11856e6ee9a9.png)

*Any help in this issue will be awesome, thank you!*

**Comment by joyarunraj** [comment]
Hi,

In case you havent allowlisted your domain in QuickSight yet, you would need to do that first, for embedding to work: https://docs.aws.amazon.com/quicksight/latest/user/approve-domain-for-dashboard-embedding.html.

If you have already allowlisted your domain, and you are still facing issues, please reach out to QuickSight support team, with your AWS account id, HAR file, error screenshot, through: https://aws.amazon.com/contact-us/. We can't directly help you in debugging in an open forum, as we would need sensitive information to check the issue further.

**Comment by tinyfly** [comment]
Make sure you are using http or https as matching the domain whitelist. I had an issue where I was logging in my app with `https` but it was then redirecting to `http` I didn't notice the change and my QuickSight embed refused to load because I had only whitelisted the `https` version.

**Comment by grchougule** [comment]
@dongtong were you able to figure out the error ? I am also having the same issues. when calling the quicksight embed URL from my react app, I am getting the same response as attached in the image above. Also, using directly the embed URL in browser, I am able to view the dashboard
