### ISSUE TITLE
TypeError: Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by rominasteinberg** [awslabs/amazon-quicksight-embedding-sdk#69]
Hi. I'm embedding a dashboard without issues, when I add :

` dashboard.setParameters({param: myParam});`

I get this message: 
```
angular.js:12332 TypeError: Cannot read property 'postMessage' of null
    at u.value (quicksight-embedding-js-sdk.min.js:1)
```
Any ideas why this could be happening? Thanks

**Comment by joyarunraj** [comment]
you could try setting parameters once the dashboard is loaded. You can listen to when a dashboard load is complete through: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-4-setup-load-callback-optional.

Alternatively, you could also set parameters before dashboard load, by setting it through the options. eg: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-2-configure-embedding

**Comment by rominasteinberg** [comment]
Great, problem solved. Thanks!
