### ISSUE TITLE
Make dark dialog background optional

### ISSUE THREAD

**Issue by rsquires** [awslabs/amazon-quicksight-embedding-sdk#7]
Could the dark background presented with dialogs become optional? When embedded in a site, user interactions can caused Quicksight dialogs to be presented at the top of the iframe. Unless there is a way to auto-scroll the frame to the dialog, the user is presented with a seemingly black screen. This can be confusing.

**Comment by cxiangna** [comment]
We've introduced SHOW_MODAL_EVENT to solve this problem

Note: With AutoFit height enabled, the dashboard's modal (such as modal shown when selected "Export to CSV" for a Table visual) could be hidden if the dashboard content is larger than the screen. To solve the issue, you can add the following code to auto-scroll the focus to the modal.

dashboard.on("SHOW_MODAL_EVENT", () => {
    window.scrollTo({
        top: 0 // iFrame top position
    });
});
