### ISSUE TITLE
iFrame height calculation problem

### ISSUE THREAD

**Issue by tinyfly** [awslabs/amazon-quicksight-embedding-sdk#70]
It appears as though iFrame height calculation only triggers when the dashboard needs to be taller to fit everything but doesn't recalculate when need it gets shorter. This leaves situations where you could have huge empty space below the  dashboard because the iFrame is too tall.

Example:
- I've got `width: '100%', height: 'AutoFit'` which will calculate and set the height attribute of the embedded iframe (e.g. 894).
-  If I open the filter and it causes the visuals to reflow into a single tall column because of width constraints the height attribute is recalculated correctly and the height is increased (e.g. 4956). 
- However, if I then close the filter and the visuals reflow back to their original layout the height isn't decreased so the iframe height stays at 4956 instead of being recalculated back down to 894. 

See screen recording:
https://user-images.githubusercontent.com/91300/107072143-95c0d800-679a-11eb-9a48-fe8132ce89cd.mov

**Comment by joyarunraj** [comment]
Thanks for bringing this to our attention. We are tracking this issue internally, and will post an update, once we have a fix.

**Comment by joyarunraj** [comment]
Could you try using `iframeResizeOnSheetChange: true` option: https://github.com/awslabs/amazon-quicksight-embedding-sdk#iframeresizeonsheetchange-element-optional, in combination with `height: AutoFit`, to see if that helps with your issue. We released this option in our latest JS SDK v1.0.15. Do let us know your feedback, on whether this helped solve your issue.

**Comment by zzhengyi-amazon** [comment]
Hello,

Resolve this issue as no response for 10 months. 

Please contact AWS Support to cut a ticket to QuickSight Embedding team if you could not fix the issue using iframeResizeOnSheetChange: true.

Thanks.

**Comment by tinyfly** [comment]
With the latest version of the JS SDK the `iframeResizeOnSheetChange: true` option does indeed seem to fix the bug I reported above.

Sorry for the late response, we're just now getting back around to the embedded quicksight project. Thanks for the fix!

**Comment by vovan-st** [comment]
I'm working with AWS QuickSight Embedding SDK 2.2.2. The best solution I found is to set `resizeHeightOnSizeChangedEvent` option to `true`:
```
      height: "AutoFit",
      resizeHeightOnSizeChangedEvent: true,
```
Unfortunately, all setting for prior versions like defining `loadingHeight` or turning on `iframeResizeOnSheetChange` etc. didn't work for me.

**Comment by bwelkin** [comment]
`loadingHeight` is no longer supported in the version 2. When you use `resizeHeightOnSizeChangedEvent : true`, the `height` value you set acts as the loading height. (`AutoFit ` is no longer supported in the version 2).

For reference: https://github.com/awslabs/amazon-quicksight-embedding-sdk/blob/master/OPTIONS_DIFFERENCES_V1_TO_V2.md#-height-autofit-optional--loadingheight-string-optional
