### ISSUE TITLE
feature request: URL actions in an embedded dashboard should open in the whole window (not just iframe)

### ISSUE THREAD

**Issue by kjpgit** [awslabs/amazon-quicksight-embedding-sdk#72]
Hi,

We have a QS embedded dashboard that has URL actions.  Some of these actions are set to open in the "same tab".  Unfortunately, opening in new tabs or windows is not an option for us.  (We are using a desktop electron app and/or have a heavyweight browser application)

current behavior: clicking a URL action only changes the iframe, not the entire window.

expected behavior: clicking a URL action changes the entire window (iframe and its parent)

We have a kludgy workaround as follows:

1) URL action goes to https://$same_embedding_origin/redirect?target=foo.com

2) The page returned from step 1) can now set `top.location = "foo.com"` because it is the same origin as iframe top container

3) The browser loads foo.com in the full window.

However, a small problem with this kludge is it adds an extra event in the browser history.   

Ideally, the SDK would be able to listen for URL action messages so we can open them without a redirect step.

**Comment by chaudharivijay** [comment]
We have a planned feature where the customers can get a callback via Javascript SDK when the user uses URL actions.

**Comment by nabilarbouz** [comment]
Hi @chaudharivijay. Is there a timeline on when that feature will be out? Thanks.

**Comment by jiajing28** [comment]
You can build the desired behavior of navigating the parent app using the new Embedded Callback Action methods in SDK v2.3.0+. 

With Embedded Callback Action, you can set a new Action on the visual that will trigger a callback in the embedded context. This Action can be set with a Datapoint Menu trigger meaning it will show up as a menu item in the datapoint context menu. When this new option within the datapoint context menu is clicked, the value of the datapoint will be send to your application through a callback. You can then parse the desired information from the datapoint and transition your application accordingly. 

You can reference how to get started [here](https://aws.amazon.com/blogs/business-intelligence/build-a-seamless-interaction-between-your-application-and-embedded-amazon-quicksight-dashboards-and-visuals-using-embedded-callback-actions/).
