### ISSUE TITLE
How to pass a dynamic parameter on an Embedded Dashboard?

### ISSUE THREAD

**Issue by sarmientoj24** [awslabs/amazon-quicksight-embedding-sdk#73]
I would like to have the embedded dashboard automatically filter or generate the analyses based on a parameter.

For example, if I have a list of names in my website, if I click the name "John Doe", it would redirect me to his profile that has an embedded quicksight dashboard where in it only shows graphs where name = John Doe and not for all data.

Is this possible?

**Comment by chaudharivijay** [comment]
Please consider using the `parameters` option in the javascript SDK to achieve this.

https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-6-update-parameter-values-optional

**Comment by domkm** [comment]
Filtering on the client does not seem like a secure option. From my reading of the documentation, it appears that [this](https://docs.aws.amazon.com/quicksight/latest/user/quicksight-dev-rls-tags.html) is the recommended approach.
