### ISSUE TITLE
Add support for currently active sheet

### ISSUE THREAD

**Issue by jeroenmeulendijks** [awslabs/amazon-quicksight-embedding-sdk#75]
With the support of `StatePersistenceEnabled: true` in the call to `getDashboardEmbedUrl` it might be that the embedded dashboard is opened on any sheet that is available on the dashboard.

Problem I run into is that there's no way for me to know on which sheet the dashboard is opened after I enable the `StatePersistenceEnabled`. I can only get a callback when the active sheet is changed, but this callback isn't executed the moment the dashboard is opened. So unless I miss something I cannot get the active sheet when the dashboard is opened which I would need to correctly display my custom TAB control.

My use case:
- I create my own TAB control to go through the sheets on a dashboard because this enhances the user experience in our use case. Next to TABS there are also buttons (and other controls) which sets certain parameters on the dashboard so an end-user is able to quickly get the data he wants. So we have a 'controls' section of our own to control filtering/parameters which are used on the dashboard. Main reason for this is that QuickSIght doesn't supply all the controls we would like to use.

So I see a couple of possible solutions:
- Add an API which I can use to query the currently active sheet
- Call the 'sheet changed' callback also when the dashboard is opened (Might be a bit of a hack on your side as there's no sheet changed action?!)
- Probably other solutions possible as well.... :)

**Comment by jeroenmeulendijks** [comment]
Thought for a moment that the `sheetId` option in version 1.0.15 might help me in the way that I could set it to an invalid value and than as stated by the documentation:
_In case the sheet id value is invalid, the first sheet of the dashboard will be loaded._

But apparently when you enable _StatePersistenceEnabled_ in the backend it overwrites this behavior.

**Comment by jeroenmeulendijks** [comment]
Is this something that will be picked up in the near future? (PS. Can I, and will it help, if I supply a pull request?)

**Comment by Dhairyasarous** [comment]
I have added an internal tracker for this feature request. We'll update this once it gets prioritized.

**Comment by bwelkin** [comment]
`getSelectedSheetId ` action in Version 2 returns the id of the currently selected sheet.

Example
```
const embeddingContext = await createEmbeddingContext();
// ...
const embeddedDashboard = await embeddingContext.embeddedDashboard(...);
// ...
const selectedSheetId = await embeddedDashboard.getSelectedSheetId();
console.log(`Currently selected sheet id is "${selectedSheetId}".`);
```

**Comment by mukeshkdangi** [comment]
@bwelkin We still see the issue.  for first time when default sheet is loaded, these apis does not return anything
