### ISSUE TITLE
Hide powered by Quicksight logo in the footer

### ISSUE THREAD

**Issue by Srinivas-Prabhu** [awslabs/amazon-quicksight-embedding-sdk#77]
How do use the SDK to hide the "Powered by Quicksight" logo in the footer?

**Comment by joyarunraj** [comment]
We currently do not support hiding "Powered by Quicksight" logo, via JS SDK. Please reach out to QuickSight support, with your usecase for removing the footer, through: https://aws.amazon.com/contact-us/. We can't directly help you in debugging in an open forum, as we would need sensitive information to understand, and sync up with you on the usecase for this.
