### ISSUE TITLE
IFrame is continuously growing in size

### ISSUE THREAD

**Issue by jeroenmeulendijks** [awslabs/amazon-quicksight-embedding-sdk#82]
We have been running version 1.0.15 for some time already but today we ran into an issue (Without changing any code!)

With the following settings:
scrolling: 'no',
height: 'AutoFit',
iframeResizeOnSheetChange: true,
loadingHeight: '0px',

I see the following behavior.
- While loading the dashboard we set the height of the iframe to 0 px because we do not want to see the QuickSight loading screen as that doesn't match our website style.
- When the dashboard is loaded we remove our loading screen and display the dashboard.
- The AutoFit setting used to set the height correctly, but since today (or at least very recent, as in last couple of days) we see that the iFrame size is expanding every second!

When debugging the issue it looks like we get a resize event every second and we can also see (through the Chrome developer tools) that the height of the iFrame is growing and growing.

**A side effect of this resizing is that the dashboard becomes completely useless as you cannot click any filters or graphs (because of the events going on in the backend)**

For now I disabled the 'AutoFit' feature and implemented a quick and dirty hack on our side to show the dashboards. In short I listen to the resize event and get the size from there to set the parent iFrame container size accordingly. But only this change would cause the same resize loop, so we break the loop by not resizing if the size change of the height is less than 32px.

We observed that the size increases every time with 16px. Of course this is a quick hack and I would love to see this fixed in quicksight. I assume something changed in the backend code (not in this NPM module) as the version of this module hasn't changed. But this behavior is only present when dashboards are embedded, therefore the issue is filed here!

**Comment by econtentmaps** [comment]
I'm getting this now, too, all of a sudden. +1 (and thanks for the "hack"/tip @jeroenmeulendijks

**Comment by econtentmaps** [comment]
Hi @jeroenmeulendijks I was hoping you could elaborate on your fix a little. I'm not sure which specific event to look for? I couldn't find any resize events in Chrome, but I'm a bit new to front-end stuff, so probably missing something obvious :)

**Comment by jeroenmeulendijks** [comment]
Hi @econtentmaps, below is a snippet of the code I'm using to work around the issue. Note: I copied part of my code and didn't test it so it might contain typos!

`
import { embedDashboard } from 'amazon-quicksight-embedding-sdk';

    const embedOptions = {
      url,
      container: document.getElementById('dashboardContainer'),
      scrolling: 'no',
      // Since 15-06-2021 it seems that setting this to 'AutoFit' will cause the iframe to continuously expand.
      // Therefore we ignore this setting and on resize event we set the correct height manually
      // height: 'AutoFit',
      iframeResizeOnSheetChange: true,
      loadingHeight: '0px',
      locale: 'en-US',
      footerPaddingEnabled: true,
      printEnabled: false,
      sheetTabsDisabled: true,
    };
    const dash = embedDashboard(embedOptions);
    dash.on('resize', (size) => {
      const { iframeHeight } = this.state;

      // HACK: to prevent resizing the iframe forever! Resizing triggers another resize, etc, etc
      const sizeDifference = Math.abs(size.height - iframeHeight);
      if (sizeDifference >= 32) {
        // Plus 32px for the 'Powered by QuickSight' logo, so we do not get a scrollbar in the iframe
        this.setState({ iframeHeight: size.height + 32 });
      }
    });
`
I do not think it's related with this issue but, we set the loadingHeight to 0px because we run a dark mode website so the white loading screen of QuickSight doesn't fit our colorscheme. We show a custom loading screen and the moment the dashboard is loaded (determined by the 'load' event) we remove our loading screen.

Hope this gives an idea of what I implemented.

**Comment by econtentmaps** [comment]
@jeroenmeulendijks legend! thank you so much. Pretty sure it's AWS end. It happened a while ago and then just stopped. Feels like a service-side regression bug.

**Comment by dariakovpak** [comment]
Hi! My team and I are experiencing this issue as well. We first encountered it on 6/18. Sheets, visuals and controls become non-responsive to clicks, which is a real issue for us.

**Comment by ngocmanh1712** [comment]
We are experiencing with this issue when click on maximize an graph or table. I also tried the hack but it return "iframeHeight not found".

**Comment by jeroenmeulendijks** [comment]
> We are experiencing with this issue when click on maximize an graph or table. I also tried the hack but it return "iframeHeight not found".

@ngocmanh1712 I copied pieces of code from a react component. So in order to have the code working you should have iframeHeight as part of the state of the component like:
```
class QuicksightEmbedDashboard extends Component {
  constructor(props) {
    super(props);

    this.state = {
      iframeHeight: 0,
    };
  }
.. Other functions for your component
}
```

**Comment by ngocmanh1712** [comment]
> > We are experiencing with this issue when click on maximize an graph or table. I also tried the hack but it return "iframeHeight not found".
> 
> @ngocmanh1712 I copied pieces of code from a react component. So in order to have the code working you should have iframeHeight as part of the state of the component like:
> 
> ```
> class QuicksightEmbedDashboard extends Component {
>   constructor(props) {
>     super(props);
> 
>     this.state = {
>       iframeHeight: 0,
>     };
>   }
> .. Other functions for your component
> }
> ```

I have tried but the size of returned event is smaller than I expected. It just 74px

**Comment by jeroenmeulendijks** [comment]
@ngocmanh1712 Sadly I'm not an expert on this module and I only managed to create a workaround which works in my case. If it doesn't work in your case I'm afraid I cannot help you.

I also created a 'Support Ticket' in my AWS account to see if it helps this issue. As I would love to remove the hack and hopefully it will help others as well.

**Comment by ngocmanh1712** [comment]
> @ngocmanh1712 Sadly I'm not an expert on this module and I only managed to create a workaround which works in my case. If it doesn't work in your case I'm afraid I cannot help you.
> 
> I also created a 'Support Ticket' in my AWS account to see if it helps this issue. As I would love to remove the hack and hopefully it will help others as well.

hope to hear response soon from AWS

**Comment by dariakovpak** [comment]
@jeroenmeulendijks AWS support replied and said that they deployed a hotfix yesterday, I tested and indeed iframe doesn't grow in size anymore. After that, I wanted to add `iframeResizeOnSheetChange: true`  since I noticed they added this option in the last release. I updated the package, but this option doesn't change anything for me. The iframe expands when sheet is longer, but doesn't go back to the original size if you come back to a different smaller sheet. I was wondering if it works for you after the hotfix?

**Comment by jeroenmeulendijks** [comment]
> @jeroenmeulendijks AWS support replied and said that they deployed a hotfix yesterday, I tested and indeed iframe doesn't grow in size anymore. After that, I wanted to add `iframeResizeOnSheetChange: true` since I noticed they added this option in the last release. I updated the package, but this option doesn't change anything for me. The iframe expands when sheet is longer, but doesn't go back to the original size if you come back to a different smaller sheet. I was wondering if it works for you after the hotfix?

Indeed it seems to be fixed, although I didn't receive any update on my ticket with AWS. (I will double check with AWS, would love to see the response AWS gave to you @dariakovpak)

On the issue of resizing the iFrame: I know others had/have issues with that as well. At the moment it's working fine for me and I use the following options:
`
    const embedOptions = {
      scrolling: 'no',
      height: 'AutoFit',
      iframeResizeOnSheetChange: true,
      loadingHeight: '0px',
      footerPaddingEnabled: false,
      printEnabled: false,
      sheetTabsDisabled: true,
    };
`
(I removed setting of the URL and container because that should be set always and I do not think the way you set it would have influence on the iFrame behavior)

Not sure if this helps...

**Comment by jeroenmeulendijks** [comment]
Issue is still happening when you maximize a graph :(

**Comment by ngocmanh1712** [comment]
> Issue is still happening when you maximize a graph :(

that is my problem

**Comment by chaudharivijay** [comment]
The fix is pending deployment.

**Comment by jeroenmeulendijks** [comment]
Just checked it but the issue is still there.

**Comment by jeroenmeulendijks** [comment]
For me this issue has been fixed by AWS :)
