### ISSUE TITLE
How to remove powered by quicksight logo in footer?

### ISSUE THREAD

**Issue by MKBLR23** [awslabs/amazon-quicksight-embedding-sdk#83]
![image](https://user-images.githubusercontent.com/10767988/125800995-31630c04-e6d5-4734-bd59-20d382fab788.png)

How to remove powered by quicksight logo in footer? Please find the attached screenshot.

**Comment by jeroenmeulendijks** [comment]
I guess the only option is: https://docs.aws.amazon.com/quicksight/latest/user/customize-and-personalize-embedded-analytics.html

See section `If your subscription to QuickSight includes an annual session pack, you can also hide the Powered by QuickSight label.`

**Comment by MKBLR23** [comment]
Thanks for quick reply.
