### ISSUE TITLE
scrolling: 'no' is ignored when iframeResizeOnSheetChange: true & height: 'AutoFit'

### ISSUE THREAD

**Issue by jayoma** [awslabs/amazon-quicksight-embedding-sdk#85]
I have upgraded to the latest (1.0.16) version to use the new `iframeResizeOnSheetChange` option, but as soon as I set this to `true`, the iframe insists upon adding its own scrollbar. This is not a problem with version 1.0.13, but that version still has the issue where the iframe doesn't shrink (hence my need for the new, `iframeResizeOnSheetChange` option). Here are my options:

```
const options = {
  url: this.dashboard.url,
  container: this.dashboardContainer.nativeElement,
  parameters: {
    userTimeZone: Intl.DateTimeFormat().resolvedOptions().timeZone
  },
  scrolling: 'no',
  height: 'AutoFit',
  iframeResizeOnSheetChange: true,
  locale: 'en-US',
  footerPaddingEnabled: true
};
```

**Comment by jayoma** [comment]
Update! It looks like this issue goes away if I set `footerPaddingEnabled: false`. But then the 'Powered by QuickSight' tag overlays my visuals. Although.. upon page load, the iframe's scrollbar is visible for just a blip, then goes away; kind of annoying. I guess this combo is the least of the evils, but hopefully I've given you guys enough clues to chase the problem.

**Comment by jayoma** [comment]
Bump. This issue is happening again (same version: 1.0.16), same config combos described above. Can one of the repo maintainers please acknowledge if this is being investigated? Thanks!

**Comment by Dhairyasarous** [comment]
I have verified that this is indeed the current behaviour are tracking the fix internally.

**Comment by Dhairyasarous** [comment]
Can you verify if this is still an issue?

**Comment by jayoma** [comment]
This is still an issue with the latest version, and I'm now seeing new issues that weren't there before. Is it possible to get on a support call with a developer, so I can share my screen and the issues we're seeing?

**Comment by bwelkin** [comment]
scrolling is deprecated in v2
