### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval'.

### ISSUE THREAD

**Issue by jarrettj** [awslabs/amazon-quicksight-embedding-sdk#87]
Hey,

Good day.

Installed module using npm.
```
npm install amazon-quicksight-embedding-sdk
```

I then include the 'node_modules/amazon-quicksight-embedding-sdk/dist/quicksight-embedding-js-sdk.js' file.

Using it in a PHP application and simply including the file above. It works if I remove the CSP. 

The module however violates my CSP which does not allow the use of eval.

Error message:
<img width="1279" alt="Screenshot 2021-08-08 at 21 39 35" src="https://user-images.githubusercontent.com/777547/128643796-57824065-1b69-45fa-b0b4-d54c5bc7eb9d.png">

Code snippet at that line:
<img width="887" alt="Screenshot 2021-08-08 at 21 39 46" src="https://user-images.githubusercontent.com/777547/128643800-28b07be8-b6e7-46a0-aa8d-c416ca5a2859.png">

Why does the script need to use eval? Might I be using it incorrectly? How do I configure it to not use eval? Thanks.

Regards.
Jarrett

**Comment by nysphere** [comment]
@jarrettj have you tried using `quicksight-embedding-js-sdk.min.js`? It does not use `eval`.

**Comment by bwelkin** [comment]
@jarrettj  have you tried using `quicksight-embedding-js-sdk.min.js`? It does not use `eval`.

**Comment by jarrettj** [comment]
Hey @bwelkin , thanks for the reply.

Where do I find that file? Used yarn to install the package. See file list below:

![Screenshot 2021-08-31 at 09 36 29](https://user-images.githubusercontent.com/777547/131462390-f6a6c713-1240-44eb-bc11-5ef3cfc0fa7b.png)

There's no minified file in there.

Regards.
Jarrett

**Comment by bwelkin** [comment]
@jarrettj How do you include the `node_modules/amazon-quicksight-embedding-sdk/dist/quicksight-embedding-js-sdk.js` file in your code?

**script tag ?**
if you are directly adding it into your html/php page, you could use
```
<script src="https://unpkg.com/amazon-quicksight-embedding-sdk@1.0.17/dist/quicksight-embedding-js-sdk.min.js"></script>
```
or, you could download `https://unpkg.com/amazon-quicksight-embedding-sdk@1.0.17/dist/quicksight-embedding-js-sdk.min.js` and add into your folder for your javascript files and consume it locally.

**import or require ?**
are you adding into your js file using `require` or `import` as seen below?

```
const QuickSightEmbedding = require("amazon-quicksight-embedding-sdk");
```

```
import { embedDashboard } from 'amazon-quicksight-embedding-sdk';
```

**Comment by jarrettj** [comment]
Hey @bwelkin, sorry for the delay, missed your email.

Used npm to install amazon-quicksight-embedding-sdk. As the documentation says. Then my assumption was that we would need to include the file from the dist folder. That was my assumption. We have a PHP application. Not using import or required.

We can download the file as you described instead. Just strange that that file is not in the dist folder of the npm installed module. That's all. Any reason why not? 

Regards.
Jarrett

**Comment by bwelkin** [comment]
Not sure. I also used `npm install` and the minified file was in the `dist` folder. We will test with different versions of `npm` to see if any difference in behavior.

We are also looking into the `eval` in the non-minified file. `webpack` is creating it. We may be able to avoid it by making some changes in webpack's config file. I will update the ticket if we are able to. Meanwhile, the minified file does not have the issue, and can be used instead of the non-minified one.

Let us know if you encounter other issues.

Thank you. Bests.

**Comment by jarrettj** [comment]
That sure is strange @bwelkin. As you can see from my screengrab,  it does not have that minified file in dist. Very strange indeed. Will pull down the minified file instead then. Skip npm on this one for the time being. 

Thanks again for the help. 

Regards.
Jarrett

**Comment by bwelkin** [comment]
The release `1.17.1` eliminates `eval` created by `webpack`.

Not able to reproduce the case where minified file is not generated after

```
npm install amazon-quicksight-embedding-sdk
```

Tried on `node 12.22.1/npm 6.14.12` and `node 6.14.4/npm 3.10.10`
