### ISSUE TITLE
emit error for CSP policy error

### ISSUE THREAD

**Issue by dalevfenton** [awslabs/amazon-quicksight-embedding-sdk#9]
If quicksight is not configured to allow embedding to a specific domain the browser stops loading the embedded dashboard because `an ancestor violates the following Content Security Policy directive: "frame-ancestors"`, but when that happens the errorCallback of `QuicksightEmbedding.embedDashboard` does not get invoked so the client cannot fallback since it doesn't know an error has occurred, is there a workaround for this?

**Comment by joyarunraj** [comment]
There is no way for QuickSight to provide error callback for this case, as the QuickSight app itself will not be loaded, when the website is not allowlisted for embedding. However, we do have error callback for expired embedding URL, invalid dashboard, access restricted dashboard: https://github.com/awslabs/amazon-quicksight-embedding-sdk#step-5-setup-error-callback-optional
