### ISSUE TITLE
Get cell value upon user click

### ISSUE THREAD

**Issue by kmughal** [awslabs/amazon-quicksight-embedding-sdk#90]
Hi

I was wondering is it possible to get the text from the table cell when user click on any cell ?

Regards
kmughal

**Comment by zzhengyi-amazon** [comment]
We have a planned feature where the customers can get the text from the table cell.

**Comment by jiajing28** [comment]
You can build this capability using Embedded Callback Action methods supported in SDK v2.3.0+. Please reference this [blog](https://aws.amazon.com/blogs/business-intelligence/build-a-seamless-interaction-between-your-application-and-embedded-amazon-quicksight-dashboards-and-visuals-using-embedded-callback-actions/) on use cases and how to get started
