### ISSUE TITLE
Embedding dashboard for local development

### ISSUE THREAD

**Issue by davidkelley** [awslabs/amazon-quicksight-embedding-sdk#92]
Hi, I'm trying to develop an internal application locally and running into the fact that `localhost` cannot be added as a whitelisted domain, is there any way around this?

![image](https://user-images.githubusercontent.com/1774262/135268885-3daea327-b609-4c2e-a057-8da00f66af15.png)

**Comment by Jesse-imuzo** [comment]
@davidkelley I was able to get this working with ngrok
