### ISSUE TITLE
Responsiveness issue of Quick Sight dashboard.

### ISSUE THREAD

**Issue by lalujvarghese** [awslabs/amazon-quicksight-embedding-sdk#94]
While viewing the Quick Sight dashboard on mobile screens, the width of Search bar on the header is getting too much reduced. Also the Kebab menu on the header is not visible in container. Please refer the below screenshot.
<img width="171" alt="issue" src="https://user-images.githubusercontent.com/93310198/139201287-9015c8ee-c248-4125-bce6-9267e2baa5b9.PNG">

Suggested quick fix: Reduce the max-width of the classes 'embedding-global-nav-left-section' and 'embedding-global-nav-right-section' to 50px.

**Comment by zzhengyi-amazon** [comment]
Thank you for reporting the issue. We fixed the issue with a recent update.
