### ISSUE TITLE
Feat: Support embedding in hybrid mobile apps

### ISSUE THREAD

**Issue by adamduren** [awslabs/amazon-quicksight-embedding-sdk#98]
As it stands currently it does not appear to be possible to embed Quick Sight charts in a Hybrid (Web) Mobile Application. Embedded Webviews such as Capacitor and Cordova either use special protocols `ionic://`, `capacitor://` or urls such as `https://localhost` all of which the QuickSight Admin section for `Domains and Embedding` rejects.

Is there a known workaround for this or plans to support mobile embedding?

**Comment by adamduren** [comment]
@bwelkin is this the correct place to make such a request? If not could you please point me in the correct direction?

**Comment by tulpun** [comment]
@adamduren Thank you for reaching out. We would like to get more information regarding your use-case. 

Could you please contact us through AWS customer support so we can follow up on this: https://aws.amazon.com/contact-us/

**Comment by adamduren** [comment]
Submitted with Case ID 9532490901.

**Comment by Phenomenan** [comment]
@adamduren did you find a solution for this problem.

**Comment by bwelkin** [comment]
`GenerateEmbedUrlForRegisteredUser` API action to obtain the embed url now supports dynamically adding allowed domains while making the API request.
 
 See [the API reference](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GenerateEmbedUrlForRegisteredUser.html#API_GenerateEmbedUrlForRegisteredUser_RequestSyntax). Also see [examples](https://docs.aws.amazon.com/quicksight/latest/user/embedded-dashboards-for-authenticated-users-step-2.html).

`https://localhost` should be supported.

Resolving the issue as it is not related to the functionality of `amazon-quicksight-embedding-sdk` package.

Please contact [AWS customer support](https://aws.amazon.com/contact-us/) is you need assistance on domain allowlisting.
