### ISSUE TITLE
Undo Redo is always enabled (clickable) ( in quicksight it appears but is disabled (non clickable) until user does something )

### ISSUE THREAD

**Issue by cBevilaqua** [awslabs/amazon-quicksight-embedding-sdk#99]
In Quicksight embedded, when we use the undoRedoDisabled: false option, the button shows as expected but is has a small different behavior from the non embedded Quicksight. The behavior in Quicksight is the button appears but stays in disabled state (non clickable) until the users does something in the panels. Although in the embedded version, the button shows but is always enabled (clickable).

**Comment by bwelkin** [comment]
Thank you for reporting the issue.

**Comment by bwelkin** [comment]
I am not able to repro the issue. Undo/Redo buttons remain disabled until I make changes on controls. Tried with state persistence both on and off, control filters with parameter and no parameter.

Are you still observing the issue? If so, could you provide the embed options you use.

Thank you.
